### ISSUE TITLE
ModuleNotFoundError: No module named 'openai.types.beta.threads.message_content'

### ISSUE THREAD

**Issue by tginart** [unclecode/crawl4ai#1]
I get `ModuleNotFoundError: No module named 'openai.types.beta.threads.message_content'`

Presumably, you are using an older version of `openai` package. Which is the right version number?

Cool project!

**Comment by unclecode** [comment]
This already has resolved, plz check again the recent release

**Comment by unclecode** [comment]
I close this issue, if you face with similar case, plz let me know
