### ISSUE TITLE
Scraping issue

### ISSUE THREAD

**Issue by dustinwloring1988** [unclecode/crawl4ai#10]
I tried to scrape https://www.nbcnews.com/world and it would not return anything?

**Comment by unclecode** [comment]
I tried and it works. Also look at this image, I suggest first try it using crawl4ai.com, if doesn't work definitely is a bug. Anyway can you share with me your code?

![image](https://github.com/unclecode/crawl4ai/assets/12494079/6395d5e1-9f22-4977-9667-747859de6928)

**Comment by unclecode** [comment]
@dustinwloring1988  Any update on this? If its resolved then I close the issue.
