### ISSUE TITLE
typo in readme example

### ISSUE THREAD

**Issue by jackmac92** [unclecode/crawl4ai#100]
Under "Execute JS, Filter Data with CSS Selector, and Clustering" the example has:
`from crawl4ai.chunking_strategy import CosineStrategy`
and seems like that should be:
`from crawl4ai.extraction_strategy import CosineStrategy`

unless it is like a "Brown M&M's clause" for self debugging

**Comment by unclecode** [comment]
Thx @jackmac92 noted, and btw we are releasing 0.3.0 this week, 100% async and bunch of cool future, stay tuned.
