### ISSUE TITLE
Crawl4ai Hard dependencites

### ISSUE THREAD

**Issue by TomerLankri** [unclecode/crawl4ai#102]
Hi guys,
I started embedding your lib to my project, when i added it to requirements i started getting non stop errors on dependencies:
The conflict is caused by:
    The user requested fastapi==0.111.1
    crawl4ai 0.2.77 depends on fastapi==0.111.0

The conflict is caused by:
    The user requested pydantic==2.2.1
    fastapi 0.111.0 depends on pydantic!=1.8, !=1.8.1, !=2.0.0, !=2.0.1, !=2.1.0, <3.0.0 and >=1.7.4
    openai 1.11.0 depends on pydantic<3 and >=1.9.0
    pydantic-settings 2.0.3 depends on pydantic>=2.0.1
    crawl4ai 0.2.77 depends on pydantic==2.7.4

and its endless.
It seems like you added hard restrictions ("==") on libraries instead of ~= and its making it impossible to add to a project.

How can i resolve this?

example requierments.txt
```
alembic==1.11.3
apideck==1.2.3
apscheduler==3.10.4
cached-property==1.5.2
celery==5.3.5
cruft==2.15.0
email-validator==2.0.0.post2
emails==0.6
fastapi==0.111.0
greenlet==3.0.3
gunicorn==21.2.0
importlib-metadata==4.2.0
importlib-resources==5.12.0
mysql-connector-python==8.0.26
openai==1.11.0
passlib==1.7.4
plaid-python==15.5.0
postmarker==1.0
py-dotenv==0.1
pydantic==2.2.1
pydantic_core==2.6.1
pydantic-settings==2.0.3
pylint==2.17.5
pymysql==1.1.0
pytest-asyncio==0.23.5.post1
python-jose==3.3.0
python-multipart==0.0.7
pywatchman==1.4.1
sentry-sdk==1.43.0
stripe==6.0.0
uvicorn==0.22.0
numpy~=1.26.4
pandas~=2.2.2
requests~=2.31.0
scikit-learn~=1.5.1
tldextract==5.1.2
crawl4ai @ git+https://github.com/unclecode/crawl4ai.git
```

**Comment by unclecode** [comment]
@TomerLankri Thanks for sharing this and using our library in your project. The new version is expected to be released by today or tomorrow, and it has been fully converted into asynchronous version. Although you can still use the sync version, we definitely recommend the new one as it is much faster and has undergone a lot of improvements. I have also shared with you the core requirements.txt that you need for this project. While waiting for new version, please feel free to adjust the requirements.txt to the one below and run it again. 

```
aiosqlite==0.20.0
html2text==2024.2.26
lxml==5.3.0
litellm==1.48.0
numpy==2.1.1
pillow==10.4.0
playwright==1.47.0
selenium==4.25.0
python-dotenv==1.0.1
requests==2.32.3
PyYAML==6.0.2
beautifulsoup4==4.12.3
psutil==6.0.0
```

Just one note: for now, it's fine if you use these versions as the minimum. If you install it with higher versions in the future, it will still work. There's no issue with that. Unless we need specific things, we will discuss them in our documentation.

**Comment by unclecode** [comment]
I close this issue as the new release already resolved this case. Thx
