### ISSUE TITLE
I just wonder in doc where is AsyncWebCrawler

### ISSUE THREAD

**Issue by NicoNicoNico123** [unclecode/crawl4ai#103]
so the async method is cancel?

**Comment by unclecode** [comment]
@NicoNicoNico123 Hi, I'm sorry I don't understand your question. The Async version is available in the staging branch, and we will be moving it to the main branch today. If you look at the documentation, all the examples are using this async version. I'm not sure if I understood your question properly.

**Comment by NicoNicoNico123** [comment]
I see, as I'm using dockerhubs version of library as I can't find this class, anyway thanks for your afford

**Comment by studio-anurag** [comment]
@unclecode Please notifiy here once it is moved to main branch, will be really helpful.

**Comment by unclecode** [comment]
@studio-anurag Version 0.3.x is released, please refer to that. @NicoNicoNico123 you're welcome, For new version, Docker needs some work, so stay tuned we release the new Docker file soon.
