### ISSUE TITLE
Crawling error

### ISSUE THREAD

**Issue by BlackChila** [unclecode/crawl4ai#105]
hey and thanks for this nice package! 
am having the following issue: some websites are randomly not scraped, while others get scraped correctly. On each run of the code which websites are scraped or not varies randomly.  For the not scraped websites I get the following error:
[ERROR] 🚫 Failed to crawl https://random-website.com, error: 'NoneType' object has no attribute 'get'. 

I save the .html files after scraping and the websites which are affected by this bug are saved in an html file with just ['', None] contained in the file. 

tried to update all packages and also setup a new conda environment, but it didnt fix the issue. I am using WebCrawler, not the AsyncWebCrawler

**Comment by unclecode** [comment]
@BlackChila Would you please share the link of the page you experienced this?

**Comment by BlackChila** [comment]
hey unclecode, thanks for your answer" I experience this on multiple pages and i can access the pages manually, so i am not blocked. Also it varies randomly if i can access the page or not, on some run it accesses it, sometimes not, so i do not think it is an issue regarding the page itself. It affects eg https://www.alange-soehne.com/eu-de or https://www.alpina-automobiles.com/de/, but other times not. in total it affects 20-30 % of my crawled websites

**Comment by unclecode** [comment]
@BlackChila Thx for sharing, Please do us a favor and try using the asynchronous method. Let's see if you get something similar with it or not. If you still face issues, then we'll start to do the stress test by crawling a set of links and websites to see when such things happen. However, let's just try it with asynchronous and let me know about it first. Thank you.

**Comment by RhonnieAl** [comment]
@unclecode Getting the same NoneType error. Here are the logs:

[LOG] 🕸️ Crawling https://www.reuters.com/markets/us/global-markets-view-usa-pix-2024-08-29/ using AsyncPlaywrightCrawlerStrategy...
[LOG] ✅ Crawled https://www.reuters.com/markets/us/global-markets-view-usa-pix-2024-08-29/ successfully!
[LOG] 🚀 Crawling done for https://www.reuters.com/markets/us/global-markets-view-usa-pix-2024-08-29/, success: True, time taken: 0.54 seconds
[ERROR] 🚫 Failed to crawl https://www.reuters.com/markets/us/global-markets-view-usa-pix-2024-08-29/, error: Failed to extract content from the website: https://www.reuters.com/markets/us/global-markets-view-usa-pix-2024-08-29/, error: can only concatenate str (not "NoneType") to str


`
from fastapi import FastAPI, HTTPException
from crawl4ai import AsyncWebCrawler
from dotenv import load_dotenv
import base64
import asyncio

load_dotenv() 

app = FastAPI()

@app.get("/")

async def crawl(url: str = "https://www.reuters.com/markets/us/global-markets-view-usa-pix-2024-08-29/"):
    try:
        async with AsyncWebCrawler(verbose=True) as crawler:
            print("Delaying for 15 seconds...")
            await asyncio.sleep(15)
            print("Resuming...")
            result = await crawler.arun(url=url, screenshot=True)
            with open("screenshot.png", "wb") as f:
             f.write(base64.b64decode(result.screenshot))
            print("Screenshot saved to 'screenshot.png'!")
            return {"content"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)

`

**Comment by BlackChila** [comment]
Thanks @RhonnieAl for posting the same issue with the asynchronous method here!

**Comment by ojaros** [comment]
Getting the same [ERROR] 🚫 Failed to crawl  error: Failed to extract content from the website: error: can only concatenate str (not "NoneType") to str

When trying to crawl a Notion site

**Comment by xansrnitu** [comment]
+1. I am encountering this same issue.

**Comment by DhrubojyotiDey** [comment]
@unclecode Thanks for the amazing library edits. I'm having a bit of a trouble understanding the error I'm getting. In the following error the library fails to crawl a news website given a specific news topic. I have used gemini api for authentication.
The following is the below error:
LOG] 🌤️  Warming up the AsyncWebCrawler
[LOG] 🌞 AsyncWebCrawler is ready to crawl
[LOG] 🕸️ Crawling https://www.nbcnews.com/business using AsyncPlaywrightCrawlerStrategy...
[LOG] ✅ Crawled https://www.nbcnews.com/business successfully!
[LOG] 🚀 Crawling done for https://www.nbcnews.com/business, success: True, time taken: 4.51 seconds
[LOG] 🚀 Content extracted for https://www.nbcnews.com/business, success: True, time taken: 0.18 seconds
[LOG] 🔥 Extracting semantic blocks for https://www.nbcnews.com/business, Strategy: AsyncWebCrawler
[LOG] Call LLM for https://www.nbcnews.com/business - block index: 0
[LOG] Call LLM for https://www.nbcnews.com/business - block index: 1
[LOG] Call LLM for https://www.nbcnews.com/business - block index: 2
[LOG] Call LLM for https://www.nbcnews.com/business - block index: 3
[LOG] Extracted 0 blocks from URL: https://www.nbcnews.com/business block index: 3
[LOG] Extracted 0 blocks from URL: https://www.nbcnews.com/business block index: 0
[LOG] Extracted 0 blocks from URL: https://www.nbcnews.com/business block index: 1
[LOG] Extracted 0 blocks from URL: https://www.nbcnews.com/business block index: 2
[LOG] 🚀 Extraction done for https://www.nbcnews.com/business, time taken: 4.68 seconds.
Number of related items extracted: 0
[]

I have a few questions in mind.
1. Why does this error occur with every news site.(assuming I am creating a project of extracting news topics from given news sites)
2. which are the sites where it has worked previously. I have tried using the example in the library site "https://www.nbcnews.com/business" and the message was same

**Comment by mobyds** [comment]
I have the same error with the use of WebCrawler

The problem is in the file utils.py
  File "C:\Dev\GIT\civic-crawler\.venv\Lib\site-packages\crawl4ai\utils.py", line 694, in get_content_of_website_optimized
    src = img.get('src', '')
    src = img.get('src', '')
          ^^^^^^^^^^^^^^^^^^
  File "C:\Dev\GIT\civic-crawler\.venv\Lib\site-packages\bs4\element.py", line 1547, in get
    return self.attrs.get(key, default)
AttributeError: 'NoneType' object has no attribute 'get'

So I path with a Try/except:
    try:
        for img in imgs:
                src = img.get('src', '')
                if base64_pattern.match(src):
                    # Replace base64 data with empty string
                    img['src'] = base64_pattern.sub('', src)
    except Exception as e:
        pass

**Comment by unclecode** [comment]
> @unclecode Thanks for the amazing library edits. I'm having a bit of a trouble understanding the error I'm getting. In the following error the library fails to crawl a news website given a specific news topic. I have used gemini api for authentication. The following is the below error: LOG] 🌤️ Warming up the AsyncWebCrawler [LOG] 🌞 AsyncWebCrawler is ready to crawl [LOG] 🕸️ Crawling https://www.nbcnews.com/business using AsyncPlaywrightCrawlerStrategy... [LOG] ✅ Crawled https://www.nbcnews.com/business successfully! [LOG] 🚀 Crawling done for https://www.nbcnews.com/business, success: True, time taken: 4.51 seconds [LOG] 🚀 Content extracted for https://www.nbcnews.com/business, success: True, time taken: 0.18 seconds [LOG] 🔥 Extracting semantic blocks for https://www.nbcnews.com/business, Strategy: AsyncWebCrawler [LOG] Call LLM for https://www.nbcnews.com/business - block index: 0 [LOG] Call LLM for https://www.nbcnews.com/business - block index: 1 [LOG] Call LLM for https://www.nbcnews.com/business - block index: 2 [LOG] Call LLM for https://www.nbcnews.com/business - block index: 3 [LOG] Extracted 0 blocks from URL: https://www.nbcnews.com/business block index: 3 [LOG] Extracted 0 blocks from URL: https://www.nbcnews.com/business block index: 0 [LOG] Extracted 0 blocks from URL: https://www.nbcnews.com/business block index: 1 [LOG] Extracted 0 blocks from URL: https://www.nbcnews.com/business block index: 2 [LOG] 🚀 Extraction done for https://www.nbcnews.com/business, time taken: 4.68 seconds. Number of related items extracted: 0 []
> 
> I have a few questions in mind.
> 
> 1. Why does this error occur with every news site.(assuming I am creating a project of extracting news topics from given news sites)
> 2. which are the sites where it has worked previously. I have tried using the example in the library site "https://www.nbcnews.com/business" and the message was same

Hi, would you please share with me your code snippet, so I can check it for you.

**Comment by unclecode** [comment]
> I have the same error with the use of WebCrawler
> 
> The problem is in the file utils.py File "C:\Dev\GIT\civic-crawler.venv\Lib\site-packages\crawl4ai\utils.py", line 694, in get_content_of_website_optimized src = img.get('src', '') src = img.get('src', '') ^^^^^^^^^^^^^^^^^^ File "C:\Dev\GIT\civic-crawler.venv\Lib\site-packages\bs4\element.py", line 1547, in get return self.attrs.get(key, default) AttributeError: 'NoneType' object has no attribute 'get'
> 
> So I patch with a Try/except: try: for img in imgs: src = img.get('src', '') if base64_pattern.match(src): # Replace base64 data with empty string img['src'] = base64_pattern.sub('', src) except Exception as e: pass

@mobyds This is interesting, would you please share the url caused this issue? Thx

**Comment by mobyds** [comment]
https://chantepie.fr/

**Comment by unclecode** [comment]
@mobyds It works for me, perhaps you can share with me your code as well as you system specs.

![image](https://github.com/user-attachments/assets/66388ccb-b982-43b6-90b4-7bd4de656741)

```python
async def main():
    async with AsyncWebCrawler(verbose=True, headless = True) as crawler:
        url = "https://chantepie.fr/"
        result = await crawler.arun(
            url=url,
            bypass_cache=True,
            screenshot = True
        )
        
        # Save screenshot to file
        with open(os.path.join(__data, "chantepie.png"), "wb") as f:
            f.write(base64.b64decode(result.screenshot))
        
        print(result.markdown)
```
 
```
[LOG] 🌤️  Warming up the AsyncWebCrawler
[LOG] 🌞 AsyncWebCrawler is ready to crawl
[LOG] 🕸️ Crawling https://chantepie.fr/ using AsyncPlaywrightCrawlerStrategy...
[LOG] ✅ Crawled https://chantepie.fr/ successfully!
[LOG] 🚀 Crawling done for https://chantepie.fr/, success: True, time taken: 5.08 seconds
[LOG] 🚀 Content extracted for https://chantepie.fr/, success: True, time taken: 0.29 seconds
[LOG] 🔥 Extracting semantic blocks for https://chantepie.fr/, Strategy: AsyncWebCrawler
[LOG] 🚀 Extraction done for https://chantepie.fr/, time taken: 0.32 seconds.
```

**Comment by mobyds** [comment]
Iy was with WebCrawler, not with

**Comment by DhrubojyotiDey** [comment]
@unclecode Hi

> > @unclecode Thanks for the amazing library edits. I'm having a bit of a trouble understanding the error I'm getting. In the following error the library fails to crawl a news website given a specific news topic. I have used gemini api for authentication. The following is the below error: LOG] 🌤️ Warming up the AsyncWebCrawler [LOG] 🌞 AsyncWebCrawler is ready to crawl [LOG] 🕸️ Crawling https://www.nbcnews.com/business using AsyncPlaywrightCrawlerStrategy... [LOG] ✅ Crawled https://www.nbcnews.com/business successfully! [LOG] 🚀 Crawling done for https://www.nbcnews.com/business, success: True, time taken: 4.51 seconds [LOG] 🚀 Content extracted for https://www.nbcnews.com/business, success: True, time taken: 0.18 seconds [LOG] 🔥 Extracting semantic blocks for https://www.nbcnews.com/business, Strategy: AsyncWebCrawler [LOG] Call LLM for https://www.nbcnews.com/business - block index: 0 [LOG] Call LLM for https://www.nbcnews.com/business - block index: 1 [LOG] Call LLM for https://www.nbcnews.com/business - block index: 2 [LOG] Call LLM for https://www.nbcnews.com/business - block index: 3 [LOG] Extracted 0 blocks from URL: https://www.nbcnews.com/business block index: 3 [LOG] Extracted 0 blocks from URL: https://www.nbcnews.com/business block index: 0 [LOG] Extracted 0 blocks from URL: https://www.nbcnews.com/business block index: 1 [LOG] Extracted 0 blocks from URL: https://www.nbcnews.com/business block index: 2 [LOG] 🚀 Extraction done for https://www.nbcnews.com/business, time taken: 4.68 seconds. Number of related items extracted: 0 []
> > I have a few questions in mind.
> > 
> > 1. Why does this error occur with every news site.(assuming I am creating a project of extracting news topics from given news sites)
> > 2. which are the sites where it has worked previously. I have tried using the example in the library site "https://www.nbcnews.com/business" and the message was same
> 
> Hi, would you please share with me your code snippet, so I can check it for you.

Below is the code snippet I used for extraction. I find the issue most common with hindustantimes and NDTV. The news block is not getting extracted completely.



url1 = "https://www.nbcnews.com/news/world/live-blog/live-updates-hamas-leader-yahya-sinwar-possibly-killed-gaza-rcna175922"
url2 = "https://www.hindustantimes.com/world-news/israelhamas-war-live-updates-palestine-israel-latest-news-hamas-militant-group-attack-101696723677129.html"

related_content = []
os.environ['GEMINI_API_KEY'] = userdata.get('my_key')

async def process_urls():
    async with AsyncWebCrawler(verbose=True) as crawler:
        for url in urls:
            # Perform extraction for each URL
            result = await crawler.arun(
                url=url1,
                extraction_strategy=LLMExtractionStrategy(
                    provider="gemini/gemini-pro",
                    bypass_cache=True,
                    api_token=os.environ['GEMINI_API_KEY'],
                    instruction="Extract only content related to Israel and hamas war and extract URL if available"
                ),
            )

            if result.extracted_content is not None:
                try:
                    extracted_data = json.loads(result.extracted_content)
                    related_content.extend(extracted_data)  # Append extracted data for each URL
                except json.JSONDecodeError as e:
                    print(f"Error decoding JSON for {url}: {e}")
                    print(f"Raw extracted content: {result.extracted_content}")  # Debug raw content
            else:
                print(f"No content extracted by the LLM for {url}")

# Execute the asynchronous function
asyncio.run(process_urls())

print(f"Number of related items extracted: {len(related_content)}")
combined_data = [item.get('content') for item in related_content]
print(combined_data)

**Comment by unclecode** [comment]
> Iy was with WebCrawler, not with AsyncWebCrawler

@mobyds  Oh, I see. Yes, I think it's better to switch to async because I very soon plan to remove the synchronous version. Additionally, I want to cut the dependency on Selenium and stick with Playwright. So, anyway, if there are any other issues, don't hesitate to reach out. Thank you for trying our library.

**Comment by mobyds** [comment]
> > Iy was with WebCrawler, not with AsyncWebCrawler
> 
> @mobyds Oh, I see. Yes, I think it's better to switch to async because I very soon plan to remove the synchronous version. Additionally, I want to cut the dependency on Selenium and stick with Playwright. So, anyway, if there are any other issues, don't hesitate to reach out. Thank you for trying our library.

OK, and thanks a lot for this very useful lib

**Comment by unclecode** [comment]
You're welcome @mobyds
