### ISSUE TITLE
Please respect robots.txt

### ISSUE THREAD

**Issue by Joshix-1** [unclecode/crawl4ai#107]
when crawling a website the robots.txt should be respected.

**Comment by BradKML** [comment]
Sometimes circumventing censorship requires flexibility. It should be an option tho

**Comment by archer-321** [comment]
> Sometimes circumventing censorship requires flexibility. It should be an option tho

`robots.txt` is not a means to censor anyone. Censorship means that you're prevented from expressing ideas or other content, and you're not expressing yourself when scraping a website.

If a website blocks a user agent in its `robots.txt` file, it means that the providers *ask you* not to scrape their website.
Even wget respects this preference (by default), so it's only fair to ask a general-purpose scraping tool to at least do the same by default.

**Comment by aravindkarnam** [comment]
@Joshix-1 This is on the roadmap and it will be configurable.

**Comment by BradKML** [comment]
@memoryhash there is a difference between open access (telling `Disallow` to get bent) vs spamming server request (respecting `Crawl-delay` out of courtesy), but people mix the latter with the former and that is very unfortunate.
For @archer-321 censorship is not just blocking freedom to express opinions, but also stopping the freedom to archive for historical purposes (looking at Internet Archive). People will throw lawyers just to try memory-hole the public.

**Comment by slatian** [comment]
@memoryhash Unenforceable soft boundaries are about politeness and respect. And there are enough admins out there to make your life hard if you aren't polite.

The only "winners" to an arms race would be the ones with the most money to throw at the problem and that is none of us, there is a reason the internet agreed on this one little seamless text file.
