### ISSUE TITLE
[DOUBT] Pagination Supported ?

### ISSUE THREAD

**Issue by Greatz08** [unclecode/crawl4ai#114]
It would be great if it supports pagination . I wanted to use this solution to scrape whole lengthy documentations of some great open source projects for making easy knowledge base which i can feed to llm for getting answer's related to that project or using it as updated knowledgebase for llm (as you know llm info can get outdated very quickly) . 
This will become great knowledge base creation kind of solution for me personally plus many others can use for same task as knowledge is and will be the limiting factor with llm's altho llm's can be connected with internet with tools still giving full knowledge base is much better because llm might not take wise decision in getting correct required info from internet plus there are many other reasons too  :-))

**Comment by unclecode** [comment]
Hello, thank you so much for using our library. Let me remind you that for all this kind of pagination or loading more, we lead you to pass a JavaScript code to be executed on the page and then continue the crawling process. There are different ways that you can do that. If you check our examples, you will find two approaches. One approach is quite simple, let's say the page has a button at the bottom, called Load More. You click the button, then more data will be appeared. And then you can continue this as much as you want, and then crawl the whole information. Another way is when the page data will re-render again when you click to the next page. It's not like additive. Instead, the back end creates new data, and renders the new page. For that one, we have multiple session crawl. That means you can create a session after crawling, where the browser stays for you, you can run your JavaScript code, and you can keep extracting the data. Both examples are there. Here I'd like to share with you one sample example of how we can run JavaScript code. However, if you go and refer to our examples, you will find exactly how to do this. Don't hesitate if you have any difficulties. You can share your code and I can help you. Thank you so much.

```python
async def simple_example_with_running_js_code():
    print("\n--- Executing JavaScript and Using CSS Selectors ---")
    async with AsyncWebCrawler(verbose=True) as crawler:
        js_code = [
            "const loadMoreButton = Array.from(document.querySelectorAll('button')).find(button => button.textContent.includes('Load More')); loadMoreButton && loadMoreButton.click();"
        ]
        result = await crawler.arun(
            url="https://www.nbcnews.com/business",
            js_code=js_code,
            bypass_cache=True,
        )
        print(result.markdown[:500])  # Print first 500 characters
```
