### ISSUE TITLE
A docs page is broken

### ISSUE THREAD

**Issue by vanetreg** [unclecode/crawl4ai#121]
The code section of:
https://crawl4ai.com/mkdocs/examples/summarization/
is broken, pls. fix it

**Comment by aravindkarnam** [comment]
@vanetreg The page is loading fine for me. Can you expand on what you mean by broken? Do you mean that example code provided there is not working as expected?

**Comment by vanetreg** [comment]
> @vanetreg The page is loading fine for me. Can you expand on what you mean by broken? Do you mean that example code provided there is not working as expected?

@aravindkarnam 
Yes, exactly: "example code provided there is not working as expected"

**Comment by unclecode** [comment]
@vanetreg Thx for the report, I think there is something totally wrong with this page, I will fix it this week.
