### ISSUE TITLE
bro ,browser select options ? 

### ISSUE THREAD

**Issue by ZengMingDa** [unclecode/crawl4ai#141]
bro ,browser select options ? 

"IE 11 is not supported. For an optimal experience visit our site on another\nbrowser."

**Comment by unclecode** [comment]
Hi, could you please let me know what URL you're trying to crawl and details about your operating system, such as whether it's a Windows machine, Mac, or Ubuntu? I'll then test it and provide you with the results. Thank you.

**Comment by DengyiLiu** [comment]
Maybe try 
"print(f"Basic crawl result: {result1.markdown[:500]}")"
rather than 
"print(f"Basic crawl result: {result1.markdown[:100]}")" 
the first one works, the second one will show "IE 11 is not supported" due to some issues

**Comment by DengyiLiu** [comment]
Hi unclecode, I also meet this issue:
"{
  "index": 0,
  "tags": [],
  "content": "IE 11 is not supported. For an optimal experience visit our site on another\nbrowser."
}"
, I'm running this code:
from crawl4ai.extraction_strategy import JsonCssExtractionStrategy
import json

async def main():
    schema = {
        "name": "News Articles",
        "baseSelector": "article.tease-card",
        "fields": [
            {
                "name": "title",
                "selector": "h2",
                "type": "text",
            },
            {
                "name": "summary",
                "selector": "div.tease-card__info",
                "type": "text",
            }
        ],
    }

    async with AsyncWebCrawler(verbose=True) as crawler:
        result = await crawler.arun(
            url="https://www.nbcnews.com/business",
            extraction_strategy=JsonCssExtractionStrategy(schema, verbose=True)
        )
        extracted_data = json.loads(result.extracted_content)
        print(f"Extracted {len(extracted_data)} articles")
        print(json.dumps(extracted_data[0], indent=2))

asyncio.run(main())
using a Ubuntu on WSL, would appreciate your answer

**Comment by thetesttoy** [comment]
我也遇到该问题请问改如何解决？

**Comment by unclecode** [comment]
@DengyiLiu I'm sorry for the delayed message. I had a similar issue created by another member here and answered it, but missed this one. I'll bring the conversation here, as this issue was created sooner. As I explained, this seems to be related to your Playwright installation. When I test the code on my Mac, everything works well, and you have the option to use it. I wondered why it's trying to use Internet Explorer instead of the default Chromium. Would you upgrade your library to the new version and try again to see if you encounter the same issue?

**Comment by thetesttoy** [comment]
> 嗨，叔叔，我也遇到了这个问题：“{ ”index“： 0， ”tags“： []， ”content“： ”IE 11 不支持。要获得最佳体验，请在其他\n浏览器上访问我们的网站。 }“ ，我正在运行以下代码：
> 
> ```
> import json
> 
> async def main():
>     schema = {
>         "name": "News Articles",
>         "baseSelector": "article.tease-card",
>         "fields": [
>             {
>                 "name": "title",
>                 "selector": "h2",
>                 "type": "text",
>             },
>             {
>                 "name": "summary",
>                 "selector": "div.tease-card__info",
>                 "type": "text",
>             }
>         ],
>     }
> 
>     async with AsyncWebCrawler(verbose=True) as crawler:
>         result = await crawler.arun(
>             url="https://www.nbcnews.com/business",
>             extraction_strategy=JsonCssExtractionStrategy(schema, verbose=True)
>         )
>         extracted_data = json.loads(result.extracted_content)
>         print(f"Extracted {len(extracted_data)} articles")
>         print(json.dumps(extracted_data[0], indent=2))
> 
> asyncio.run(main()) ```
> 
> 
> using a Ubuntu on WSL, would appreciate your answer
> ```

The specific command used was "playwright codegen --browser=chromium https://www.bing.com/，Switch to the search engine of your choice.

**Comment by unclecode** [comment]
@thetesttoy We currently have a `browser_type` flag that can be passed when creating an `AsyncWebCrawler`, with options including WebKit, Chrome, and Firefox.
