### ISSUE TITLE
Local Hosted Open Source LLM Support for Extraction (like models from Ollama)

### ISSUE THREAD

**Issue by luxmar** [unclecode/crawl4ai#144]
As the whole project claims that it is open scource wouldn't it make sense to provide also support for using open source LLMs (e.g., from Ollama) for extraction tasks? As for now, if I interpreted the documentaiton right, there is only support for LLMs from OpenAI and Groq. Groq uses Open Source LLMs but it is just another paid cloud servide. With e.g., Ollama for Huggingface Transformers, one yould host LLMs on local machines which improves privacy and lowers costs in case of small models.

**Comment by unclecode** [comment]
@luxmar Hi, I would like to remind you that we have been supporting Ollama from the very beginning. When creating a crawler using a large language model extraction strategy, you can simply pass the name of the model you want to use through Ollama following this pattern `ollama/llama3.2`. Behind the scenes, we utilize the Litellm library that supports over 100 LLM providers, including Ollama or HuggingFace. For example, in the following code, I'm demonstrating the same example that is also featured in our documentation, but I'm using Ollama Local LLM. I hope this can help clarify the answer.

```python
async def extract_structured_data_using_llm():
    print("\n--- Extracting Structured Data with LLM ---")

    async with AsyncWebCrawler(verbose=True) as crawler:
        result = await crawler.arun(
            url="https://openai.com/api/pricing/",
            word_count_threshold=1,
            extraction_strategy=LLMExtractionStrategy(
                provider="ollama/llama3.2",
                api_token='nothing',
                schema=OpenAIModelFee.schema(),
                extraction_type="schema",
                instruction="""From the crawled content, extract all mentioned model names along with their fees for input and output tokens. 
                Do not miss any models in the entire content. One extracted model JSON format should look like this: 
                {"model_name": "GPT-4", "input_fee": "US$10.00 / 1M tokens", "output_fee": "US$30.00 / 1M tokens"}.""",
            ),
            bypass_cache=True,
        )
        print(result.extracted_content)
```
