### ISSUE TITLE
Integrate Hugging Face model for LLMExtractionStrategy

### ISSUE THREAD

**Issue by RiteshKB** [unclecode/crawl4ai#146]
In documentation, examples only related to OpenAI gpt-4o are provided. However I want to use opensource models of Hugging Face. Can you please provide solution for the same.

**Comment by unclecode** [comment]
Hi @RiteshKB We already covered Ollama and Huggingface, Please check this issue https://github.com/unclecode/crawl4ai/issues/144 Thx using Crawl4AI
