### ISSUE TITLE
README Example: CSS Selector Not Functioning

### ISSUE THREAD

**Issue by hitesh22rana** [unclecode/crawl4ai#148]
## Description
I've identified an issue in the Advanced Usage example in the README.md file. The current CSS selector used for extracting content from the NBC News business page is not working as intended.

Current selector: `"article.tease-card"`
Issue: This selector fails to extract any data, making the example non-functional.
This problem may confuse new users trying to understand and implement the library's advanced features. Having a working example is important for demonstrating the correct usage of the crawler.

## Expected Behavior
The example should successfully extract article descriptions from the NBC News business page.

## Actual Behavior
No content is extracted, and the example fails to demonstrate the crawler's functionality.

## Proposed Solution
I propose updating the CSS selector to `".wide-tease-item__description"`. This selector correctly targets the description text of the news articles.

## Fix
I have created a pull request to address this issue: https://github.com/unclecode/crawl4ai/pull/135

Kindly review and merge of this pull request to resolve the issue.

**Comment by unclecode** [comment]
@hitesh22rana Thanks for your suggestions. Unbeknownst to you, this has happened before, and they may change from time to time. Even if we use the one you suggested, there may be instances where they change it. To address this, we plan to pick our own Crawl4ai website for this example. We will merge your pull request to current main branch. We'll definitely consider it and add your name to our contributor list.
