### ISSUE TITLE
Instalation problem

### ISSUE THREAD

**Issue by renatoramiro** [unclecode/crawl4ai#15]
> OS: Zorin OS (ubuntu based)
> Python: 3.11.7

When I try to install the lib, below error is happening:

![Captura de tela de 2024-06-06 10-54-26](https://github.com/unclecode/crawl4ai/assets/495054/8284a655-741e-44b3-884c-3ea01a74de80)

**Comment by unclecode** [comment]
This is due to a conflict between spacy and selenium. Try to instal spacy like this `pip install spacy --no-deps` then try again.
