### ISSUE TITLE
Bad results crawling mantine docs `?t=props`

### ISSUE THREAD

**Issue by Dimfred** [unclecode/crawl4ai#156]
Hey thx for the lib :)

Playing around with it trying to crawl: `https://mantine.dev/core/button/?t=props`
If you have a quick answer why it doesn't work, that would be great, else I'll probably take a look the next days.
Cheers

**Comment by Marisa2312** [comment]
__

**Comment by unclecode** [comment]
Hi @Dimfred I am currently working on version 0.3.6. While testing the links you provided with this version, it appears to be functioning as expected at my end. However, I'm not sure what issue you're experiencing. Nevertheless, there are two options. By Monday or Tuesday, we will update the library in Pypi, but for now, you can pull the latest version from the branch "0.3.6". If you're encountering any specific error messages, I would appreciate it if you could share them with me. Thank you for trying our library.

```
[LOG] 🌤️  Warming up the AsyncWebCrawler
[LOG] 🌞 AsyncWebCrawler is ready to crawl
[LOG] 🕸️ Crawling https://mantine.dev/core/button/?t=props using AsyncPlaywrightCrawlerStrategy...
[LOG] ✅ Crawled https://mantine.dev/core/button/?t=props successfully!
[LOG] 🚀 Crawling done for https://mantine.dev/core/button/?t=props, success: True, time taken: 2.69 seconds
[LOG] 🚀 Content extracted for https://mantine.dev/core/button/?t=props, success: True, time taken: 0.09 seconds
[LOG] 🔥 Extracting semantic blocks for https://mantine.dev/core/button/?t=props, Strategy: AsyncWebCrawler
[LOG] 🚀 Extraction done for https://mantine.dev/core/button/?t=props, time taken: 0.10 seconds.
```

**Comment by Dimfred** [comment]
I will try you version and check the results. I don't have issues accessing the link or something, the content is just not there, like the main parts which are present on that page are missing (the table with the props).

**Comment by unclecode** [comment]
@Dimfred Glad to hear that.
