### ISSUE TITLE
Page.goto: Timeout 60000ms exceeded.

### ISSUE THREAD

**Issue by jmontoyavallejo** [unclecode/crawl4ai#157]
could you please add the possibility to change the timeout, in some places and containers could take more than 60 seconds
crawl4ai/crawl4ai/async_crawler_strategy.py

 line 251

 response = await page.goto(url, wait_until="domcontentloaded", timeout=60000)

**Comment by unclecode** [comment]
Hi @jmontoyavallejo  We've already added this feature, thank you for the suggestion. It's a really good idea. Although we haven't released the new version yet, you can currently pull from this "0.3.6" branch, but by Monday or Tuesday, we will also update the library in Pypi.

**Comment by dhifafaz** [comment]
> Hi @jmontoyavallejo We've already added this feature, thank you for the suggestion. It's a really good idea. Although we haven't released the new version yet, you can currently pull from this "0.3.6" branch, but by Monday or Tuesday, we will also update the library in Pypi.

how to do it after updating the version?

**Comment by jmontoyavallejo** [comment]
In the invocation of the function like crawler.arun(...,page_timeout=120000) it worked for me
