### ISSUE TITLE
Incorrect Markdown Formatting in Extracted Content

### ISSUE THREAD

**Issue by truonghoangnguyen** [unclecode/crawl4ai#161]
I encountered an issue with the markdown formatting in the extracted content when using the crawl4ai library. The image markdown syntax seems to be incorrectly escaped, leading to improperly formatted images in the output.
```
![\\"Nobel](\\"https://photo2.tinhte.vn/data/attachment-
files/2024/10/8480950_giai-thuong-nobel-ai-su-mo-nhat-va-tinh-thuc-
tien.jpg\\"/)
```
Expected:
```
![Nobel](https://photo2.tinhte.vn/data/attachment-files/2024/10/8480950_giai-thuong-nobel-ai-su-mo-nhat-va-tinh-thuc-tien.jpg)
```

Steps to Reproduce (ipynb file)
```
import asyncio
from crawl4ai import AsyncWebCrawler

async def main():
    async with AsyncWebCrawler(verbose=True) as crawler:

        result = await crawler.arun(url="https://tinhte.vn/thread/tren-tay-chuot-carbon-rog-harpe-ace-extreme-chi-47-gram-gia-hon-6-trieu.3837734/",
        css_selector="#__next > div.jsx-2814768367.thread-view > div > div.jsx-3437297739.threadpage.false > div.jsx-3437297739.section.bg-white.false > div.jsx-3437297739.fst.false > div > div > div.jsx-1103166024.thread-view--content-wrapper > main")
        
        print(result.markdown)

# Check if an event loop is already running
if not asyncio.get_event_loop().is_running():
    asyncio.run(main())
else:
    await main()
```

This is my local fix :

<img width="561" alt="image" src="https://github.com/user-attachments/assets/12d731a6-1ca1-460f-a007-73cf0bc70a9a">

Thank you for your hardwork.

**Comment by unclecode** [comment]
@truonghoangnguyen  Thank you for using Crell for AICrawl4ai. Actually, you pointed out something interesting. We spotted the issue and we already fixed it. The new version (0.3.6), which will be released tomorrow, will fix this as well. We converted to mock down before sanitizing the string. And in this version, everything is good. I tested with your link. I'll paste a picture here so you can see how it goes. Again, thank you so much.

![image](https://github.com/user-attachments/assets/f3671138-b576-46ed-9735-a48d0317d620)
