### ISSUE TITLE
All website crawling instead of just single webpage 

### ISSUE THREAD

**Issue by MSR2201** [unclecode/crawl4ai#164]
I want to know is there a way to crawl the whole website instead of single webpage.

**Comment by unclecode** [comment]
@MSR2201  Right now, we're working on our scraper engine and it will be available soon, in a few weeks, which uses the current engine to make a graph search within the page on a website and return the whole websote. There are a lot of parameters to define the depth of the crawling, a lot of filters to extract only relevant pages or filter based on the header of the page, and many more actual things. 

Right now, what you can do is when you crawl a page, we return a list of external and internal links, so you can add those internal links into a queue and start to crawl them one by one. In this way, you're building a small scraper. We already have the functions that allow you to crawl multiple links together; the name of the function is 'arun_many.'

**Comment by MSR2201** [comment]
can you give me the whole code for that.

**Comment by unclecode** [comment]
@MSR2201 Here I share with you a code based on what I suggested; however, I didn't have time to test it, so you can test it and see if it works. If there's a bug, please let me know. As I mentioned earlier, our scrapper engine will be released within a week or two, which is of high quality and at an industrial level. In the meantime, I hope this simple code can help you temporarily resolve whatever issue you're trying to address.

```python
import asyncio
from collections import deque
from typing import Dict, List, Set
from crawl4ai.models import CrawlResult
from crawl4ai import AsyncWebCrawler
from urllib.parse import urljoin, urlparse, urlunparse

class SimpleWebsiteScraper:
    def __init__(self, crawler: AsyncWebCrawler):
        self.crawler = crawler
        self.base_url = None

    def is_valid_internal_link(self, link: str) -> bool:
        if not link or link.startswith('#'):
            return False
        
        parsed_base = urlparse(self.base_url)
        parsed_link = urlparse(link)
        
        return (parsed_base.netloc == parsed_link.netloc and
                parsed_link.path not in ['', '/'] and
                parsed_link.path.startswith(parsed_base.path))

    def normalize_url(self, url: str) -> str:
        parsed = urlparse(url)
        # Remove any fragments
        parsed = parsed._replace(fragment='')
        # Ensure the path doesn't end with a slash unless it's the root
        if parsed.path.endswith('/') and len(parsed.path) > 1:
            parsed = parsed._replace(path=parsed.path.rstrip('/'))
        return urlunparse(parsed)

    def join_url(self, base: str, url: str) -> str:
        joined = urljoin(base, url)
        parsed_base = urlparse(self.base_url)
        parsed_joined = urlparse(joined)
        
        # Ensure the joined URL starts with the base path
        if not parsed_joined.path.startswith(parsed_base.path):
            # If it doesn't, prepend the base path
            new_path = parsed_base.path.rstrip('/') + '/' + parsed_joined.path.lstrip('/')
            parsed_joined = parsed_joined._replace(path=new_path)
        
        return urlunparse(parsed_joined)

    async def scrape(self, start_url: str, max_depth: int) -> Dict[str, CrawlResult]:
        self.base_url = self.normalize_url(start_url)
        results: Dict[str, CrawlResult] = {}
        queue: deque = deque([(self.base_url, 0)])
        visited: Set[str] = set()

        while queue:
            current_url, current_depth = queue.popleft()
            
            if current_url in visited or current_depth > max_depth:
                continue
            
            visited.add(current_url)
            
            result = await self.crawler.arun(current_url)
            
            if result.success:
                results[current_url] = result
                
                if current_depth < max_depth:
                    internal_links = result.links.get('internal', [])
                    for link in internal_links:
                        full_url = self.join_url(current_url, link['href'])
                        normalized_url = self.normalize_url(full_url)
                        if self.is_valid_internal_link(normalized_url) and normalized_url not in visited:
                            queue.append((normalized_url, current_depth + 1))

        return results


async def main(start_url: str, depth: int):
    async with AsyncWebCrawler() as crawler:
        scraper = SimpleWebsiteScraper(crawler)
        results = await scraper.scrape(start_url, depth)
    
    print(f"Crawled {len(results)} pages:")
    for url, result in results.items():
        print(f"- {url}: {len(result.links.get('internal', []))} internal links, {len(result.links.get('external', []))} external links")

if __name__ == "__main__":
    start_url = "https://crawl4ai.com/mkdocs"
    depth = 2
    asyncio.run(main(start_url, depth))    
```

**Comment by luisferreira93** [comment]
Hello @unclecode, great work! 👍🏻  do you have any date range for the release of this feature? Thank you

**Comment by unclecode** [comment]
@luisferreira93 Sorry for my delay. Been very busy to release 0.3.74. Right now, you can see the branch `scraper-uc` and internally we are testing. If you join our Discord, you can see the conversation over there. And also, I am adding an executor module that's designed to crawl a list of URLs extremely efficiently and adaptively react based on available resources on the computer. So there are two different things: one is this executor and the other one is the scrapper. I really want to have all of them by this year, 2024, for sure.

**Comment by ccaam1** [comment]
Hey @unclecode, really enjoying the library 🙌 ! Just wanted to ask if you had a rough timeline on the availability of this feature? Thank you!

**Comment by unclecode** [comment]
@ccaam1 thx for kind words and Scraper is planned for this month 😎 at least beta version

**Comment by aravindkarnam** [comment]
@singhdiwakar020 This feature is getting released tonight. It's called deep_crawl, stay tuned on changelog and unclecode's [twitter handle](https://x.com/unclecode) for an in-depth tutorial.

**Comment by singhdiwakar020** [comment]
Thank you so much @aravindkarnam, excited to see the new feature. i have one more question but for now https://github.com/unclecode/crawl4ai/issues/164#issuecomment-2422268309 this code works? or its better to wait for the deep_crawl

**Comment by aravindkarnam** [comment]
@singhdiwakar020 Better wait for deep_crawl, it's very memory and network efficient. Also offers a ton of functionality to crawl the pages efficiently likes filtering, sorting etc. You can also choose between strategies like breadth first, depth first vs best first traversals.

**Comment by singhdiwakar020** [comment]
sure thank you so much @aravindkarnam, Lets see!!

**Comment by pixelrakete** [comment]
I use deepcrawl and it is working perfectly. I am just stuggling to exclude specific internal links from getting crawled. I could not find the right method. I want to exclude pages like r'privacy', r'terms' or r'legal' from getting crawled. Can you please point me in the right direction.
