### ISSUE TITLE
Failed to take a screenshot. The screenshot is blank.

### ISSUE THREAD

**Issue by ns-arakawa** [unclecode/crawl4ai#167]
I found a problem with v0.3.6 where the screenshot would be blank. This problem seems to occur on sites that are reloaded using javascript like "https://0-0.energy"

I got around this by changing the source in async_crawler_strategy.py. I attached screenshot of souce code I changed

<img width="950" alt="スクリーンショット 2024-10-14 180406" src="https://github.com/user-attachments/assets/f68bff90-d3b7-4034-9814-dc8bef2bbdce">

I changed the value of the argumen for page.wait_for_timeout from 100 to 3000. I think that the appropriate value will differ depending on the site. It is better to change to changrable parameter from API.

**Comment by unclecode** [comment]
@ns-arakawa Thx for pointing this out, I am checking it right now

**Comment by unclecode** [comment]
@ns-arakawa I tested with the give URL, I can't replicate your case unfortunately, on my end it works. Can you share your exact code? Thx

**Comment by ns-arakawa** [comment]
This case was caused by Javascript in Goddy's parked domain. This was not a crawl4ai bug.
I will close this ticket

**Comment by unclecode** [comment]
Thx
