### ISSUE TITLE
You don't have permission to access xxx on this server

### ISSUE THREAD

**Issue by OpEnD17** [unclecode/crawl4ai#170]
As title said, how to solve this problem?

code:

import asyncio
from crawl4ai import AsyncWebCrawler

async def main():
    async with AsyncWebCrawler(verbose=True) as crawler:
        url = "http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024"
        result = await crawler.arun(url=url)
        print(result.markdown)

if __name__ == "__main__":
    asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
    asyncio.run(main())

error:
[LOG] 🌤️  Warming up the AsyncWebCrawler
[LOG] 🌞 AsyncWebCrawler is ready to crawl
[LOG] 🚀 Content extracted for http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024, success: True, time taken: 0.01 seconds
[LOG] 🚀 Extraction done for http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024, time taken: 0.01 seconds.
# Access Denied

You don't have permission to access "http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024" on this server.

Reference #18.d1b42e17.1729140590.88d77167 

https://errors.edgesuite.net/18.d1b42e17.1729140590.88d77167

**Comment by Mahizha-N-S** [comment]
Yeah it seems we cant scrap this website, as it has a security policy within them
`response_headers={ 
              'content-length': '457', 
              'content-security-policy': 'frame-ancestors https://www.ato.gov.au https://virtualassistant.ato.gov.au 
              https://www.beta.ato.gov.au', 
             'content-type': 'text/html', 
           'date': 'Thu, 17 Oct 2024 05:47:02 GMT', 'expires': 'Thu, 17 Oct 2024 05:47:02 GMT',
            'mime-version': '1.0', 
             'server': 'AkamaiGHost', 'x-frame-options': 'SAMEORIGIN'
           }   status_code=403
`
As you cna see here it has status-code 403 meaning forbidden error, and the website has some permission restriction!

**Comment by OpEnD17** [comment]
> Yeah it seems we cant scrap this website, as it has a security policy within them `response_headers={ 'content-length': '457', 'content-security-policy': 'frame-ancestors https://www.ato.gov.au https://virtualassistant.ato.gov.au https://www.beta.ato.gov.au', 'content-type': 'text/html', 'date': 'Thu, 17 Oct 2024 05:47:02 GMT', 'expires': 'Thu, 17 Oct 2024 05:47:02 GMT', 'mime-version': '1.0', 'server': 'AkamaiGHost', 'x-frame-options': 'SAMEORIGIN' } status_code=403 ` As you cna see here it has status-code 403 meaning forbidden error, and the website has some permission restriction!

Thank you Mahizha!

**Comment by unclecode** [comment]
@OpEnD17 @Mahizha-N-S This website you can crawl it but you should disable the "headless". 

```python
async def main():
    async with AsyncWebCrawler(verbose=True, headless=False) as crawler:
        url = "http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024"
        result = await crawler.arun(
            url=url,
            bypass_cache=True,
        )
        
        print(result.markdown)

if __name__ == "__main__":
    asyncio.run(main())
```

It will returns:
```
[LOG] 🌤️  Warming up the AsyncWebCrawler
[LOG] 🌞 AsyncWebCrawler is ready to crawl
[LOG] 🕸️ Crawling http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024 using AsyncPlaywrightCrawlerStrategy...
[LOG] ✅ Crawled http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024 successfully!
[LOG] 🚀 Crawling done for http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024, success: True, time taken: 1.60 seconds
[LOG] 🚀 Content extracted for http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024, success: True, time taken: 0.09 seconds
[LOG] 🔥 Extracting semantic blocks for http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024, Strategy: AsyncWebCrawler
[LOG] 🚀 Extraction done for http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024, time taken: 0.11 seconds.
Skip to main contentSkip To searchSkip To Alex Virtual Assistant

  * ATO Community
  * Legal Database
  * What's New
  ....
  ```
  
This happens for some website, I will find a way around. For now, set headless to False.

**Comment by Mahizha-N-S** [comment]
yes, got it now it works, with headless=False,
Just for a clarity, in what cases should we have headless=False, can we use this generally for all the website crawling?,
and at having headless=False and running the crawler does it open the url website and closes automatically by itself?
```
🚀 Crawling done for http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024/, success: True, time taken: 4.52 seconds
[LOG] 🚀 Content extracted for http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024/, success: True, time taken: 0.14 seconds
[LOG] 🔥 Extracting semantic blocks for http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024/, Strategy: AsyncWebCrawler
```

but if i close the website, which opened during scrawling it results like this
it results like this
```
[ERROR] 🚫 Failed to crawl http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024/, error: Failed to crawl http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024/: Page.wait_for_selector: Target page, context or browser has been closed
Call log:
waiting for locator("body") to be visible

INFO:__main__:url='http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024/' html='' success=False cleaned_html=None media={} links={} screenshot=None markdown=None extracted_content=None metadata=None error_message='Failed to crawl http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024/: Page.wait_for_selector: Target page, context or browser has been closed\nCall log:\nwaiting for locator("body") to be visible\n' session_id=None response_headers=None status_code=None
----------------------------------------------------
ERROR:__main__:Error in crawling http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024/, Failed to crawl http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024/: Page.wait_for_selector: Target page, context or browser has been closed
Call log:
waiting for locator("body") to be visible
 
```

**Comment by OpEnD17** [comment]
> @OpEnD17 @Mahizha-N-S This website you can crawl it but you should disable the "headless".
> 
> ```python
> async def main():
>     async with AsyncWebCrawler(verbose=True, headless=False) as crawler:
>         url = "http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024"
>         result = await crawler.arun(
>             url=url,
>             bypass_cache=True,
>         )
>         
>         print(result.markdown)
> 
> if __name__ == "__main__":
>     asyncio.run(main())
> ```
> 
> It will returns:
> 
> ```
> [LOG] 🌤️  Warming up the AsyncWebCrawler
> [LOG] 🌞 AsyncWebCrawler is ready to crawl
> [LOG] 🕸️ Crawling http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024 using AsyncPlaywrightCrawlerStrategy...
> [LOG] ✅ Crawled http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024 successfully!
> [LOG] 🚀 Crawling done for http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024, success: True, time taken: 1.60 seconds
> [LOG] 🚀 Content extracted for http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024, success: True, time taken: 0.09 seconds
> [LOG] 🔥 Extracting semantic blocks for http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024, Strategy: AsyncWebCrawler
> [LOG] 🚀 Extraction done for http://www.ato.gov.au/forms-and-instructions/tax-return-for-individuals-2024, time taken: 0.11 seconds.
> Skip to main contentSkip To searchSkip To Alex Virtual Assistant
> 
>   * ATO Community
>   * Legal Database
>   * What's New
>   ....
> ```
> 
> This happens for some website, I will find a way around. For now, set headless to False.

Thank you! It works!

**Comment by unclecode** [comment]
@Mahizha-N-S It's fine to keep the headless set to False, but when you're running it in an OS like Linux with no GUI, it doesn't make that much of a difference. However, in the new version, this has already been handled. There's a flag that I call the 'magic' flag – you set it True, and it will automagically fix the issue for you (At least most of cases 😅). I plan to release it over the weekend, as I mentioned, and it will work. We've also changed the stage for closing the page and browsers so that the browser stays open to ensure you have everything. I hope this will be helpful, but if anything else is unclear, please let me know.

**Comment by Mahizha-N-S** [comment]
@unclecode , Thanks for letting me know, sure will try it, and looking forward for you updates 😊

**Comment by unclecode** [comment]
@Mahizha-N-S We will release 0.3.72 by tomorrow. You may try it.
