### ISSUE TITLE
Missing `**kwargs` (excluded_tags) in WebScrappingStrategy.ascrap()

### ISSUE THREAD

**Issue by truonghoangnguyen** [unclecode/crawl4ai#177]
The current implementation of `WebScrappingStrategy.ascrap()`  of `async_webcrawler.py` is missing the `**kwargs` argument when calling the function. As a result, certain additional keyword arguments `excluded_tags` passed to ascrap() are not forwarded to `WebScrappingStrategy`, which can limit the flexibility and extendability of the scrapping strategy.
 
<img width="780" alt="image" src="https://github.com/user-attachments/assets/cabcc020-7ae1-4527-ba8d-1d0acc7749d5">
<img width="786" alt="image" src="https://github.com/user-attachments/assets/d7b1f0e8-b47b-472f-befc-95a961f6b105">

Thank you for you hardwork

**Comment by unclecode** [comment]
Thank you for pointing this out. Yes, actually a few days ago, I found it when I was facing the issue. It's going to be resolved, and I will include it in the new versions within one or two days. I appreciate your sharing and input. Please, continue to do so. If you'd also like, you can join our Discord and become one of our collaborators. I appreciate that.
