### ISSUE TITLE
Provide a means to block/ignore the crawler from crawling any illegal/adult pages

### ISSUE THREAD

**Issue by aravindkarnam** [unclecode/crawl4ai#18]
This is more of a feature request. Can you please look at some means to block the crawler from pulling in any illegal or adult content if any of the target URLs contain/links to them? Do you recommend using the LLM extraction strategy and go with a prompt for it? 

In my application, I collect a URL/landing page from the users and use LLM to write up a marketing brief, which will further be used for grounding the model. So just in case someone maliciously tries to enter a hazardous URL I want to catch it at the crawling stage itself.

**Comment by unclecode** [comment]
I added this to our backlog, and already found some good solution for that, so for now I close this issue
