### ISSUE TITLE
Extract only the cleaned markdown

### ISSUE THREAD

**Issue by QuangTQV** [unclecode/crawl4ai#186]
How can I extract only the cleaned markdown? Right now it contains headers, footers, advertisements, etc.

**Comment by unclecode** [comment]
@QuangTQV There are multiple flags and parameters you can use to control the level of data-cleaning you may need. Please share with me your URL, then I give you an example.

**Comment by unclecode** [comment]
I close this issue and please follow this on https://github.com/unclecode/crawl4ai/issues/181
