### ISSUE TITLE
I can't get a docker container to run :)

### ISSUE THREAD

**Issue by FractalMind** [unclecode/crawl4ai#19]
You have an awesome project going on here. It's simple but covers most use cases for AI so far

There are a few issues when I try to run the project. I'm no Python coder so I want to use a working docker container. 

First, may I suggest that you push a working image to Docker Hub? I think it will greatly push your app forward by removing as much friction as possible in using your app. 

The problem I'm having is: **I cannot have docker container working.**

My first instinct is to run `docker-compose up -d`

But I get the first problem: 
```
//docker-compose.yml
...
command: uvicorn main:app --host 0.0.0.0 --port 80 --workers $(nproc)
...
```
$(nproc) in my linux (Ubuntu 24.04) AND inside the container resolve as: `12: command not found` 

So when I start the container I get in the logs:
```
Usage: uvicorn [OPTIONS] APP
Try 'uvicorn --help' for help.
Error: Invalid value for '--workers': '$(nproc)' is not a valid integer. //"12: command not found" It's true is not a valid integer
```
If I hardcode `uvicorn main:app --host 0.0.0.0 --port 80 --workers 12` where $(nproc) evaluate to 12 in my host:

![Screenshot from 2024-06-12 16-10-35](https://github.com/unclecode/crawl4ai/assets/5481933/74fb2bb5-8ebd-43a8-8350-f49a7ea33844)

I can get the UI running. But when I run your sample demo with default values the backend crashes(same result with Postman):

```
...
#11 0x6502aca03d3a <unknown>
#12 0x6502aca2a026 <unknown>
#13 0x6502acaac8f6 <unknown>
#14 0x6502aca8d613 <unknown>
#15 0x6502aca5d4f7 <unknown>
#16 0x6502aca5de4e <unknown>
#17 0x6502acd0187b <unknown>
#18 0x6502acd05921 <unknown>
#19 0x6502acced36e <unknown>
#20 0x6502acd06482 <unknown>
#21 0x6502accd1ccf <unknown>
#22 0x6502acd2b0a8 <unknown>
#23 0x6502acd2b280 <unknown>
#24 0x6502acd3a7dc <unknown>
#25 0x726ba0d38134 <unknown>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 148, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/src/app/main.py", line 136, in crawl_urls
    results = await asyncio.gather(*futures)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/crawl4ai/web_crawler.py", line 156, in run
    html = self.crawler_strategy.crawl(url)
  File "/usr/src/app/crawl4ai/crawler_strategy.py", line 154, in crawl
    raise Exception(f"Failed to crawl {url}: {str(e)}")
Exception: Failed to crawl https://www.nbcnews.com/business: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome-headless-shell=126.0.6478.55)
```

When I try to build the docker image for Ubuntu 24.04: 
```
docker build --platform linux/amd64 -t crawl4ai .
docker run -d -p 8000:80 crawl4ai
```
I get:

```
[LOG] Loading Extraction Model for cpu device.
[LOG] Loading Multilabel Classifier for cpu device.
[LOG] Model loaded sentence-transformers/all-MiniLM-L6-v2, models/reuters, took 6.76580810546875 seconds
DEBUG:root:[LOG] Running the WebCrawler...
[LOG] 🕸️ Crawling https://www.nbcnews.com/business using LocalSeleniumCrawlerStrategy...
INFO:     172.17.0.1:32858 - "POST /crawl HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/src/app/crawl4ai/crawler_strategy.py", line 121, in crawl
    self.driver.get(url)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
#0 0x5e3677aa46aa <unknown>
#1 0x5e3677786f21 <unknown>
#2 0x5e36777c57ed <unknown>
#3 0x5e36777f6754 <unknown>
#4 0x5e36777f0fcf <unknown>
#5 0x5e36777f024a <unknown>
#6 0x5e3677751cf8 <unknown>
#7 0x5e3677a6a87b <unknown>
#8 0x5e3677a6e921 <unknown>
#9 0x5e3677a5636e <unknown>
#10 0x5e3677a6f482 <unknown>
#11 0x5e3677a3accf <unknown>
#12 0x5e36777502d6 <unknown>
#13 0x7191df2d424a <unknown>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/src/app/main.py", line 136, in crawl_urls
    results = await asyncio.gather(*futures)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/crawl4ai/web_crawler.py", line 156, in run
    html = self.crawler_strategy.crawl(url)
  File "/usr/src/app/crawl4ai/crawler_strategy.py", line 154, in crawl
    raise Exception(f"Failed to crawl {url}: {str(e)}")
```
I tried localhost instead 0.0.0.0 I tried a different port. However, the problem seems to come from the backend inside the container. 

**I'm hoping you can guide me to a successful build or even better if you could push a working image to Docker Hub for those who don't code in Python :) With ❤️ from Canada**

Here are my host specs:

> # System Details Report
> ---
> 
> ## Report details
> - **Date generated:**                              2024-06-12 16:14:30
> 
> ## Hardware Information:
> - **Hardware Model:**                              ASUSTeK COMPUTER INC. Z10PE-D16 Series
> - **Memory:**                                      64.0 GiB
> - **Processor:**                                   Intel® Xeon® E5-2609 v3 × 12
> - **Graphics:**                                    Intel® Arc™ A750 Graphics (DG2)
> - **Disk Capacity:**                               7.0 TB
> 
> ## Software Information:
> - **Firmware Version:**                            3801
> - **OS Name:**                                     Ubuntu 24.04 LTS
> - **OS Build:**                                    (null)
> - **OS Type:**                                     64-bit
> - **GNOME Version:**                               46
> - **Windowing System:**                            Wayland
> - **Kernel Version:**                              Linux 6.8.0-35-generic

**Comment by unclecode** [comment]
@FractalMind I am on it, actually has been some issues with Docker, so building it again in different approach, soon I will update.

**Comment by unclecode** [comment]
@FractalMind I have updated Dockerfile and requirements,txt, please check the new version and let me know please.

**Comment by FractalMind** [comment]
Hey @unclecode thank you so much for the quick answer. I pulled `main` but after building the docker container:

> fryser@fryser-desktop:/media/fryser/RAID1/PROJECTS/vendors/crawl4ai$ docker-compose up -d --build
> WARN[0000] /media/fryser/RAID1/PROJECTS/vendors/crawl4ai/docker-compose.yml: `version` is obsolete 
> [+] Building 750.7s (14/14) FINISHED                                                                                                                                                                                                                        docker:default
>  => [web internal] load build definition from Dockerfile                                                                                                                                                                                                              0.0s
>  => => transferring dockerfile: 2.13kB                                                                                                                                                                                                                                0.0s
>  => [web internal] load .dockerignore                                                                                                                                                                                                                                 0.0s
>  => => transferring context: 2B                                                                                                                                                                                                                                       0.0s
>  => [web internal] load metadata for docker.io/library/python:3.10-slim-bookworm                                                                                                                                                                                      0.0s
>  => [web internal] load build context                                                                                                                                                                                                                                 0.1s
>  => => transferring context: 979.74kB                                                                                                                                                                                                                                 0.1s
>  => [web 1/9] FROM docker.io/library/python:3.10-slim-bookworm                                                                                                                                                                                                        0.0s
>  => CACHED [web 2/9] WORKDIR /usr/src/app                                                                                                                                                                                                                             0.0s
>  => [web 3/9] RUN apt-get update &&     apt-get install -y --no-install-recommends     wget     git     curl     unzip     gnupg     xvfb     ca-certificates     apt-transport-https     software-properties-common &&     rm -rf /var/lib/apt/lists/*              49.6s
>  => [web 4/9] COPY requirements.txt .                                                                                                                                                                                                                                 0.0s
>  => [web 5/9] RUN pip install --no-cache-dir -r requirements.txt &&     pip install --no-cache-dir spacy torch onnxruntime uvicorn &&     python -m spacy download en_core_web_sm                                                                                   554.3s
>  => [web 6/9] RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&     sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' &&     apt-get update   62.8s
>  => [web 7/9] COPY . .                                                                                                                                                                                                                                                0.6s
>  => [web 8/9] RUN pip install --no-cache-dir -e .[all]                                                                                                                                                                                                                8.3s
>  => [web 9/9] RUN crawl4ai-download-models                                                                                                                                                                                                                           28.9s
>  => [web] exporting to image                                                                                                                                                                                                                                         46.1s
>  => => exporting layers                                                                                                                                                                                                                                              46.1s
>  => => writing image sha256:3dcd70beeee4e86ba269837c902dfa69c893b14822e65e86fc65916e5c58044a                                                                                                                                                                          0.0s
>  => => naming to docker.io/library/crawl4ai-web                                                                                                                                                                                                                       0.0s
> [+] Running 1/1
>  ✔ Container crawl4ai-web-1  Started 

 I get this log from the container:

> INFO:     Waiting for child process [2634]
> INFO:     Child process [2634] died
> INFO:     Waiting for child process [2653]
> INFO:     Child process [2653] died
> INFO:     Waiting for child process [2654]
> INFO:     Child process [2654] died
> INFO:     Waiting for child process [2712]
> INFO:     Child process [2712] died
> INFO:     Waiting for child process [2611]
> INFO:     Child process [2611] died
> INFO:     Waiting for child process [2612]
> INFO:     Child process [2612] died
> INFO:     Waiting for child process [2613]
> INFO:     Child process [2613] died
> INFO:     Waiting for child process [2614]
> INFO:     Child process [2614] died
> INFO:     Waiting for child process [2615]
> INFO:     Child process [2615] died
> INFO:     Waiting for child process [2629]
> INFO:     Child process [2629] died
> INFO:     Waiting for child process [2630]
> INFO:     Child process [2630] died
> INFO:     Waiting for child process [2632]
> INFO:     Child process [2632] died
> INFO:     Waiting for child process [2653]
> INFO:     Child process [2653] died
> INFO:     Waiting for child process [2712]
> INFO:     Child process [2712] died
> INFO:     Waiting for child process [2612]
> INFO:     Child process [2612] died
> INFO:     Waiting for child process [2614]
> INFO:     Child process [2614] died
> INFO:     Waiting for child process [2629]
> INFO:     Child process [2629] died
> INFO:     Waiting for child process [2632]
> INFO:     Child process [2632] died
> INFO:     Waiting for child process [2712]
> INFO:     Child process [2712] died
> INFO:     Waiting for child process [2614]
> INFO:     Child process [2614] died
> INFO:     Waiting for child process [2632]
> INFO:     Child process [2632] died
> Process SpawnProcess-210:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
>     self.run()
>   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
>     target(sockets=sockets)
>   File "/usr/local/lib/python3.10/site-packages/uvicorn/supervisors/multiprocess.py", line 63, in target
>     return self.real_target(sockets)
>   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
>     return asyncio.run(self.serve(sockets=sockets))
>   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
>   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
>     await self._serve(sockets)
>   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
>     config.load()
>   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
>     self.loaded_app = import_from_string(self.app)
>   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
>     module = importlib.import_module(module_str)
>   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/usr/src/app/main.py", line 41, in <module>
>     app.mount("/mkdocs", StaticFiles(directory="site", html=True), name="mkdocs")
>   File "/usr/local/lib/python3.10/site-packages/starlette/staticfiles.py", line 59, in __init__
>     raise RuntimeError(f"Directory '{directory}' does not exist")
> RuntimeError: Directory 'site' does not exist


Please note: I had to hardcode 12 to resolve $(nproc)
```
version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80 --workers 12
    ports:
      - "80:80"
    environment:
      - PYTHONUNBUFFERED=1
```

I'm I doing something wrong? 
If you have a working container at home can you create a public account at [https://hub.docker.com/](https://hub.docker.com/) and push your working image to the public?

It might take 10 minutes but it would be of a great help to everyone :)

Thank you so much for your time

**Comment by FractalMind** [comment]
If I navigate inside the container and I create a folder site at `/usr/src/app/site`

I can get the UI working.
![2024-06-21_17-58](https://github.com/unclecode/crawl4ai/assets/5481933/4bde36a3-89bf-4c9d-920d-5a8c0f7ed536)

But if I execute the default action, the container logs gives me a backend error:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
>     result = await app(  # type: ignore[func-returns-value]
>   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
>     return await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
>     await super().__call__(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
>     raise exc
>   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
>     await self.app(scope, receive, _send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
>     await self.simple_response(scope, receive, send, request_headers=headers)
>   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 148, in simple_response
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
>     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
>     raise exc
>   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
>     await app(scope, receive, sender)
>   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
>     await route.handle(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
>     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
>     raise exc
>   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
>     await app(scope, receive, sender)
>   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
>     response = await func(request)
>   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
>     raw_response = await run_endpoint_function(
>   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
>     return await dependant.call(**values)
>   File "/usr/src/app/main.py", line 137, in crawl_urls
>     results = await asyncio.gather(*futures)
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/src/app/crawl4ai/web_crawler.py", line 156, in run
>     html = self.crawler_strategy.crawl(url)
>   File "/usr/src/app/crawl4ai/crawler_strategy.py", line 217, in crawl
>     raise Exception(f"Failed to crawl {url}: {str(e)}")

**Comment by unclecode** [comment]
@FractalMind Thank you for reporting the issue. I’ve just resolved it. Please update to version 0.2.6. The issue was in the Dockerfile, as we recently created proper documentation using the MkDocs library. We needed to run the `mkdocs build` command to create the site folder containing the documentation. Now, if you run it and go to `/mkdocs`, you'll see proper documentation as well. Let me know if there are any problems.

**Comment by FractalMind** [comment]
Good job @unclecode, I confirm that the container can now run. 
But the backend is not stable. It will process this request about 5 times

```
{
    "urls": [
        "https://xxxxxxx.xxx"
    ],
    "include_raw_html": false,
    "bypass_cache": false,
    "extract_blocks": false,
    "word_count_threshold": 10,
    "extraction_strategy": "NoExtractionStrategy",
    "chunking_strategy": "FixedLengthWordChunking",
    "chunking_strategy_args": {},
    "css_selector": "",
    "screenshot": false,
    "verbose": true
}
```

Then the backend will crash out of nowhere and won't process any other request :(

> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
>     result = await app(  # type: ignore[func-returns-value]
>   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
>     return await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
>     await super().__call__(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
>     raise exc
>   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
>     await self.app(scope, receive, _send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
>     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
>     raise exc
>   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
>     await app(scope, receive, sender)
>   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
>     await route.handle(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
>     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
>     raise exc
>   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
>     await app(scope, receive, sender)
>   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
>     response = await func(request)
>   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
>     raw_response = await run_endpoint_function(
>   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
>     return await dependant.call(**values)
>   File "/usr/src/app/main.py", line 144, in crawl_urls
>     results = await asyncio.gather(*futures)
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/src/app/crawl4ai/web_crawler.py", line 159, in run
>     html = self.crawler_strategy.crawl(url)
>   File "/usr/src/app/crawl4ai/crawler_strategy.py", line 217, in crawl
>     raise Exception(f"Failed to crawl {url}: {str(e)}")
> Exception: Failed to crawl https://www.dantech.ca: Message: invalid session id
> Stacktrace:
> #0 0x5e42b0320c7a <unknown>
> #1 0x5e42b0003c71 <unknown>
> #2 0x5e42b004253d <unknown>
> #3 0x5e42b00734a4 <unknown>
> #4 0x5e42b006dd0f <unknown>
> #5 0x5e42b006cf8a <unknown>
> #6 0x5e42affcea88 <unknown>
> #7 0x5e42b02e724b <unknown>
> #8 0x5e42b02eb2f1 <unknown>
> #9 0x5e42b02d2afe <unknown>
> #10 0x5e42b02ebe52 <unknown>
> #11 0x5e42b02b779f <unknown>
> #12 0x5e42affcd066 <unknown>
> #13 0x775615bd724a <unknown>

Any idea on how to fix it?

**Comment by unclecode** [comment]
@FractalMind You are welcome, let me take a look at it, are u still in the same specs u shared before?

**Comment by unclecode** [comment]
I assume you have already been able to run it on Docker, considering you raised another issue regarding concurrent requests. I will close this one and continue addressing the other issue with you. Thank you for building with Crawl4ai.
