### ISSUE TITLE
Feature Request: Support Username/Password for Proxy

### ISSUE THREAD

**Issue by truonghoangnguyen** [unclecode/crawl4ai#197]
Currently, the proxy parameter only accepts the server as a proxy setting. However, my proxy requires a username and password for authentication. I would like to request support for adding username and password to the proxy parameter.

This would allow the integration of authenticated proxies, which is necessary for environments where proxy servers require login credentials.

**Comment by unclecode** [comment]
@truonghoangnguyen Thx for the suggestion, already added in the new version 0.3.72 (Will be released soon)

```py
async def proxy():
    async with AsyncWebCrawler(headless = True, proxy_config = {
            "server": "PROXY_SERVER_ADDRESS",
            "username": "USR",
            "password": "PWD"
        }) as crawler:
        url = "https://www.nbcnews.com/business"
        result = await crawler.arun(
            url=url,
            bypass_cache=True,
            word_count_threshold = 10,
        )

    print("Done")
```
