### ISSUE TITLE
Issues running on Colab

### ISSUE THREAD

**Issue by ali-chaudhry8** [unclecode/crawl4ai#2]
It would be very helpful if you can share a Colab. I seem to be getting too many dependency issues. Latest one: 
AttributeError: module 'crawl4ai' has no attribute 'fetch_page'

**Comment by yaohongfenglove** [comment]
It seems that there is an error in the example code in README.md. Change **crawl4ai** to **crawler**, as shown below:

```python
crawler = WebCrawler(db_path='crawler_data.db')

# Single page crawl
single_url = UrlModel(url='https://hk.jobsdb.com/job/72444652', forced=False)
result = crawler.fetch_page(
    single_url,
    ...
)
```

**Comment by unclecode** [comment]
@yaohongfenglove  @ali-chaudhry8  I am releasing the new version by tonight or tomorrow, all these things resolved, also Colab version works now. Above all, it became 10x faster!! Will update soon
