### ISSUE TITLE
result.markdown is missing words when there's a span enclosed in a h1 tag in the crawled page

### ISSUE THREAD

**Issue by aravindkarnam** [unclecode/crawl4ai#20]
Sometimes a span is introduced in headings to either change text color, bold or italicize certain words in a heading or paragraph etc. Such spans enclosed in HTML text/heading tags seem to get left out in `result.markdown`.

Consider the following pages:
1. https://urbanpiper.com, inside h1 tag `<h1>"Manage your food delivery channels on <span class="purple-text">one dashboard</span></h1>"`, when this page is crawled and result is produced, in `result.markdown` "one dashboard" is missing, leading to incomplete sentence.
2. https://reelsify.app, inside h1 tag `<h1>"Engage your customers with short <span>snackable</span> videos"</h1>`, this same bug is reproducible.(the word "snackable" is missing in result.markdown)

This seems like a bug.  Please let me know if you need any help in reproducing this bug.

**Comment by unclecode** [comment]
@aravindkarnam Very interesting! Then I'll flatten those header tags that contain inner tags. Spans or similar tags within headers don't add extra value. A header tag already signifies importance, so emphasizing parts within it is redundant. I'll convert something like `<h1>Manage your food delivery channels on <span class="purple-text">one dashboard</span></h1>` to `<h1>Manage your food delivery channels on one dashboard</h1>`.

I'll update it soon. Thanks for sharing.

**Comment by aravindkarnam** [comment]
@unclecode Raised a PR for this. Please review.

**Comment by unclecode** [comment]
@aravindkarnam All done, and now you can check the utils.py. Again, appreciate your contribution. Please stay connected and share any other issues you face with Crawl4ai. I close this PR.
