### ISSUE TITLE
Detect and accept cookies/privacy settings popups

### ISSUE THREAD

**Issue by si2w** [unclecode/crawl4ai#202]
I need to take screenshots of websites, but often, pop-ups for privacy settings are in the way. It would be great to detect them and click the button before taking the screenshot.

**Comment by unclecode** [comment]
@si2w  Very interesting suggestion, The new version, we have already added a new parameter: `remove_overlay_elements`. When you set it, it tries to decompose all the overlays in the pop-up and will even try to click on the close button if there is something over it. Then it starts to extract the content, and consequently, taking a screenshot will also be affected by that. This is a new feature; let's see how it goes. If you find any bugs, please let us know.

```py
async def main():
    async with AsyncWebCrawler(headless = False) as crawler:
        url = "https://janineintheworld.com/places-to-visit-in-central-mexico"
        result = await crawler.arun(
            url=url,
            bypass_cache=True,
            word_count_threshold = 10,
            screenshot = True
            remove_overlay_elements=True
        )
        # Save markdown to file
        with open(os.path.join(__data, "mexico_places.md"), "w") as f:
            f.write(result.markdown)

    print("Done")
```
