### ISSUE TITLE
Support for free LLMs?

### ISSUE THREAD

**Issue by ComputingVictor** [unclecode/crawl4ai#204]
Hello,

I was wondering if there are plans to support free LLMs maybe with Ollama in Crawl4AI? Currently, the examples and documentation focus on paid APIs like OpenAI, but it would be great if we could integrate with local or free models. 

Is this something that could be implemented or currently supported? Any guidance would be appreciated.

Thanks!

**Comment by unclecode** [comment]
Hi, of course - behind the scenes we use `litellm`. You can use any open-source or proprietary large language model. For `ollama`, just pass `ollama/MODEL_NAME` and then use it. We definitely support this one.
