### ISSUE TITLE
How to summerize a website?

### ISSUE THREAD

**Issue by FractalMind** [unclecode/crawl4ai#21]
I have to handle a request whose goal is to summarize a website and extract its [offers, services, and products] in one concise paragraph. This information might be across multiple pages like: (about, services, contact)

I'm still learning AI and crawling. 

**What would be the best strategy to accomplish this goal? Is Crawl4Ai suitable for this or is there a better strategy?**

Thank you for your time :)

**Comment by unclecode** [comment]
@FractalMind Let me think of an example and then share the code here for you. I believe there is one way to do it with the current version. I will update you soon. Thanks for using the library.

**Comment by unclecode** [comment]
@FractalMind Right now, one way to summarize a page is to use LLMExtractionStrategy. Check the example [here](https://github.com/unclecode/crawl4ai/blob/main/docs/examples/summarize_page.py). You can run this for multiple pages and then reduce all summaries into one using any LLM.

However, I'm working on the following:
- Building a sitemap for any website containing all links
- Crawling all pages recursively
- Creating a SummaryExtractionStrategy

Until then, the example I shared should help you.

**Comment by FractalMind** [comment]
For now, I crawl the main page using `chunkingStrategy: "FixedLengthWordChunking"` , then use an LLM to summarize their offer, services, and products. 

It works for now in most cases. But in the future I might need to add more pages like **service, contact, about** in the context windows. I'll close the issue, thx.
