### ISSUE TITLE
Concurrent requests

### ISSUE THREAD

**Issue by 1933211129** [unclecode/crawl4ai#221]
Hello, I would like to ask the correct way to make concurrent requests. Does direct setting`(max_concurrent_requests=10)` make concurrent requests take effect? This is my guidance from the crawl4ai assistant. However, after my tests, it seems that there are no concurrent requests, and the time to request multiple links is the time of a single request multiplied by the number of times, for example, I request 30 links, the total time is still about 30 seconds, and the results of multiple tests with different numbers of different links are the same. That's a little slow.

`import asyncio
from crawl4ai import AsyncWebCrawler
import re
async def clean_content_with_fit_markdown(urls: list):
    results = {}

    async with AsyncWebCrawler(max_concurrent_requests=10, verbose=False) as crawler:
        tasks = []  

        for url in urls:
            tasks.append(crawler.arun(  
                url=url,
                css_selector="div.main, article, p",
                keep_links=False,
                exclude_external_links=True,
                exclude_social_media_links=True,
                excluded_tags=['footer', 'small', 'address', 'aside', 'nav', 'form', 'section', 'ul', 'li', 'a'],
                page_timeout=15000
            ))

        # 执行所有任务
        results_list = await asyncio.gather(*tasks)

        for url, result in zip(urls, results_list):
            try:
                # 获取完整的 markdown 内容
                full_content = result.markdown
                if not full_content:
                    print(f"URL: {url} - 没有提取到内容\n")
                    results[url] = ""  
                    continue
                clean_text = re.sub(r'\[.*?\]\(.*?\)\s*[\n\s]*\*.*?(\n\s*\*.*?)*', '', full_content)  # 清除常见的链接和列表
                clean_text = re.sub(r"(版权所有|ICP备|联系我们|关于我们|广告|登录|注册|免责声明)", "", full_content)

                results[url] = clean_text.strip()

                print(f"URL: {url} - 清理后的内容已提取\n")

            except Exception as e:
                print(f"URL: {url} - 爬取出错: {e}\n")
                results[url] = None

    return results`
`
urls = [
    "http://www.las.cas.cn/news/tzgg/202410/t20241021_7405284.html",
    "http://www.news.cn/politics/leaders/20241030/4b1d240ea739408dbd42dcfedd81700f/c.html",
    "http://www.news.cn/politics/20241031/77c8877b112d49589fcc27c0af18ad63/c.html",
    'https://news.gmw.cn/2024-10/31/content_37647561.htm',
    'http://www.news.cn/20241030/7528b6b8ad484cc78448309e3bedfd0c/c.html',
    'https://www.bbc.com/news/articles/crez85y20zvo',
    'https://www.bistu.edu.cn/xysx/449105.html',
    'http://www.las.cas.cn/news/fwcx/202410/t20241031_7411933.html',
    'http://www.las.cas.cn/news/fwcx/202410/t20241031_7411861.html',
    'http://politics.people.com.cn/n1/2024/1101/c1001-40351585.html',
    'http://politics.people.com.cn/n1/2024/1101/c1001-40351586.html',
    'http://politics.people.com.cn/n1/2024/1101/c1001-40351587.html',
    'http://finance.people.com.cn/n1/2024/1101/c1004-40351589.html',
    'http://ent.people.com.cn/n1/2024/1101/c1012-40351604.html',
    'http://politics.people.com.cn/n1/2024/1101/c1001-40351612.html',
    'http://opinion.people.com.cn/n1/2024/1101/c1003-40351623.html',
    'http://finance.people.com.cn/n1/2024/1101/c1004-40351591.html',
    'http://world.people.com.cn/n1/2024/1101/c1002-40351601.html',
    'http://finance.people.com.cn/n1/2024/1101/c1004-40351582.html',
    'http://military.people.com.cn/n1/2024/1101/c1011-40351614.html',
    'http://military.people.com.cn/n1/2024/1101/c1011-40351579.html',
    'https://society.people.com.cn/n1/2024/1101/c1008-40351605.html',
    'http://health.people.com.cn/n1/2024/1101/c14739-40351644.html',
    'http://finance.people.com.cn/n1/2024/1101/c1004-40351627.html',
    'http://world.people.com.cn/n1/2024/1101/c1002-40351660.html',
    'http://society.people.com.cn/n1/2024/1101/c1008-40351628.html',
    'http://media.people.com.cn/n1/2024/1030/c14677-40349925.html',
    'http://finance.people.com.cn/n1/2024/1031/c1004-40350883.html',
    'http://kpzg.people.com.cn/n1/2024/1031/c404214-40350815.html',
    'http://edu.people.com.cn/n1/2024/1031/c1006-40350955.html',
]

results = asyncio.run(clean_content_with_fit_markdown(urls))
`

Above is the code I executed, thank you for your time to answer！

**Comment by unclecode** [comment]
@1933211129 Thank you for using our library. It seems the GPTs Crawl4ai AI assistant hallucinating :D. There is no such `max_concurrent_requests`, however you can use a `run_many()` function that accepts a list of URLs and processes multiple URLs at once. Note that we'll be dropping our scrapper module soon, which features multiple concurrency algorithms - not just parallel URL passing. It was designed for efficient website scraping using graph search. For now, you can use this function. I've pasted a sample code here for reference. Let me know if you have any further issues.

```python
@pytest.mark.asyncio
async def test_concurrent_crawling_performance():
    async with AsyncWebCrawler(verbose=True) as crawler:
        urls = [
            "https://www.nbcnews.com/business",
            "https://www.example.com",
            "https://www.python.org",
            "https://www.github.com",
            "https://www.stackoverflow.com"
        ]
        
        start_time = time.time()
        results = await crawler.arun_many(urls=urls, bypass_cache=True)
        end_time = time.time()
        
        total_time = end_time - start_time
        print(f"Total time for concurrent crawling: {total_time:.2f} seconds")
        
        assert all(result.success for result in results)
        assert len(results) == len(urls)
```

**Comment by 1933211129** [comment]
@unclecode Thank you for your reply. I will continue to follow the progress of this library, and thank you for your contribution to this project.

**Comment by unclecode** [comment]
You're welcome
