### ISSUE TITLE
Warnings coming from playwright-stealth

### ISSUE THREAD

**Issue by RoyLeviLangware** [unclecode/crawl4ai#244]
playwright-stealth is no longer under active delopment and causes warning because of its usage of `pkg_resources`

Moving over to a maintained fork would solve the issue:
https://github.com/tinyfish-io/tf-playwright-stealth

**Comment by unclecode** [comment]
Thanks for the suggestion. I checked and the warning's gone. The updated library will be used in the next version. Thanks again.
