### ISSUE TITLE
Crawl all website data using Sitemap for efficiency"

### ISSUE THREAD

**Issue by QuangTQV** [unclecode/crawl4ai#245]
What do you think about crawling all the data of a website using its sitemap?

**Comment by unclecode** [comment]
Hi @QuangTQV  We are currently testing a new Scraper module for Crawl4AI. It uses graph search algorithms to intelligently crawl websites, handling everything from simple blog posts to complex nested pages. It also support reading the sitemap. Whether you need to crawl an entire documentation site or extract data from multiple product pages, the Scraper will handle all the heavy lifting. Therefore, my answer to your question is an absolute yes, coming very soon.

**Comment by nick-choudhary** [comment]
@unclecode any updated on this?

**Comment by aravindkarnam** [comment]
@nick-choudhary This is available in crawl4AI now. A feature by the name deep crawl. Here's the tutorial for same

https://x.com/unclecode/status/1897661309199810853

**Comment by nick-choudhary** [comment]
Thanks @aravindkarnam for taking time to respond to the query and great work with the deepcrawling module. I still don't see the functionality of reading urls from sitemap - as that would save a lot of resources. What I am looking is something related to https://www.firecrawl.dev/playground?mode=map

Is this something on your roadmap already?

**Comment by aravindkarnam** [comment]
@nick-choudhary That's right. We currently don't have a mechanism to scrape by sitemap but has different traversal strategies to explore the entire site until configured thresholds are reached. This is on our future roadmap though.

**Comment by nick-choudhary** [comment]
Thanks @aravindkarnam for the quick response.
