### ISSUE TITLE
"CustomHTML2Text" is not defined in synchronous WebCrawler

### ISSUE THREAD

**Issue by aadityakanjolia4** [unclecode/crawl4ai#248]
<img width="895" alt="CustomHTML2Text" src="https://github.com/user-attachments/assets/fc2f5082-6fef-4646-9856-548582ccfaba">

This issue occurred  we use synchronous WebCrawler in crawl4ai==0.3.73

**Comment by unclecode** [comment]
@aadityakanjolia4 Thanks for using the library. This issue is already fixed in the new version, which will be released in a day or two.
