### ISSUE TITLE
Build issue after numpy v.0.0.2 release

### ISSUE THREAD

**Issue by nzlz** [unclecode/crawl4ai#25]
Hi @unclecode, first of all, really appreciate your efforts with this and other projects :pray:  we are testing a version of this repo internally at http://www.aware-agent.com (ill try to book some time to make a PR with couple fixes in the future)

Now, the topic of this issue is the requirements.txt file, which i see that now contains no versions - why is that? are you thinking of tagging of releasing some version of crawl4ai at some point? in that case at least, tagging all deps to fixed versions would be preferred I believe.

Regarding this specific issue, I solved it by setting numpy dep to the prior version.
Note that I am few weeks of commits behind, at  https://github.com/unclecode/crawl4ai/commit/f1b60b2016c403734bb8a53a00d901dae5acb4ff

See: https://github.com/numpy/numpy/issues/26710

My fix: https://github.com/aware-agent/crawl4ai/commit/c5d18e1f6cd02d182bf3d6a9adee932bbb575956

**Comment by unclecode** [comment]
@nzlz Thank you for your kind words and for using the project! 🙏

You're absolutely right about the versions in `requirements.txt`. I had temporarily removed them to test with different versions, but I've now fixed and committed specific versions in the latest update. I appreciate your fix regarding the numpy dependency.

Thank you for the contribution, and I'm definitely looking forward to any PRs or improvements you might have in the future. The latest update also includes several bug fixes and better Docker support, tested on various setups including Windows and different environments.

Thanks again for your support and contributions!

**Comment by nzlz** [comment]
Great :)

Closing this issue then :+1:
