### ISSUE TITLE
error: BrowserContext.new_page: Target page, context or browser has been closed

### ISSUE THREAD

**Issue by rafliekawangsha** [unclecode/crawl4ai#256]
hey unclecode, i tried running the latest image from docker, but i get this error

{
  "status": "completed",
  "created_at": 1731469472.917161,
  "result": {
    "url": "https://docs.firecrawl.dev/features/crawl",
    "html": "",
    "success": false,
    "cleaned_html": null,
    "media": {},
    "links": {},
    "screenshot": null,
    "markdown": "[ERROR] 🚫 arun(): Failed to crawl https://docs.firecrawl.dev/features/crawl, error: BrowserContext.new_page: Target page, context or browser has been closed",
    "fit_markdown": null,
    "fit_html": null,
    "extracted_content": null,
    "metadata": null,
    "error_message": "BrowserContext.new_page: Target page, context or browser has been closed",
    "session_id": null,
    "response_headers": null,
    "status_code": null
  }
}

**Comment by unclecode** [comment]
@rafliekawangsha Can you please share your code when you are sending the request. Thx

**Comment by rafliekawangsha** [comment]
docker pull unclecode/crawl4ai:latest
docker run -p 11235:11235 unclecode/crawl4ai:latest

i just run this on my terminal and open http://myipaddress:11235/docs to try the crawling

**Comment by unclecode** [comment]
ok, understood. I've made a few changes based on the issue you reported. For now, you can pull down this branch 0.3.74, or wait a bit and I'll update to a new version soon. To run your Docker, you can also increase the shared memory by using the command below.

```sh
docker run --shm-size=2gb -p 11235:11235 unclecode/crawl4ai:basic
```

Let me know if you encounter any issues. Additionally, could you please share your environment specifications with me, including your operating system and computer type?

**Comment by rafliekawangsha** [comment]
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested

i get this warning after docker run command, does it have something to do with the error?

i am running it on my laptop with windows 11, 16gb ram, i5-10300H CPU @ 2.50Hz

**Comment by unclecode** [comment]
@rafliekawangsha This weekend, I will test the docker on all 3 platforms directly, and fix it once for all.

**Comment by rafliekawangsha** [comment]
@unclecode thank you, will wait for the docker image update

**Comment by rafliekawangsha** [comment]
is there any changes on the request needed for docker? since i get 403 error when crawl but on health endpoint it works

**Comment by unclecode** [comment]
Hello @rafliekawangsha , I am going to release the new version tonight. Please try the Docker file and see if there are any changes. Let me know, please.

**Comment by jasperfue** [comment]
Hey @unclecode,

I'm still having the same problems. I've read that you are changing the docker deployments and images right now, so maybe it's not relevant anymore, but in case it is, here is some information about the problems I encountered:

Without adding an API-token I also get a 403 error, just like @rafliekawangsha explained. When providing an API-token, it works.

> _is there any changes on the request needed for docker? since i get 403 error when crawl but on health endpoint it works_

But still I get the error `Browser.new_context: Target page, context or browser has been closed` every time I hit the `/crawl` endpoint.

<details>
  <summary>docker-compose.yml</summary>

```yaml
version: '3.8'

services:
  crawl4ai:
    image: unclecode/crawl4ai:all # I've also tried unclecode/crawl4ai:latest
    ports:
      - "11235:11235"
    environment:
      - CRAWL4AI_API_TOKEN=${CRAWL4AI_API_TOKEN:-} 
      - MAX_CONCURRENT_TASKS=5
    volumes:
      - /dev/shm:/dev/shm
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
```
</details>

<details>
  <summary>Next.js API Call</summary>

```typescript
// Call Crawl4AI
const crawlResponse = await fetch("http://localhost:11235/crawl", {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    Authorization: `Bearer ${env.CRAWL4AI_API_TOKEN}`,
  },
  body: JSON.stringify({
    urls: validatedFields.data.Url,
    priority: 10,
  }),
});

if (!crawlResponse.ok) {
  return {
    message: "Failed to start crawl",
    errors: { seoUrl: ["Crawl4AI did not start successfully."] },
  };
}

const crawlData = await crawlResponse.json();
const taskId = crawlData.task_id;

// Polling
let taskResult: any = null;
const maxAttempts = 30;
const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
let attempts = 0;
while (attempts < maxAttempts) {
  await delay(2000); // Wait 2 seconds
  const statusResponse = await fetch(`http://localhost:11235/task/${taskId}`, {
    headers: {
      Authorization: `Bearer ${env.CRAWL4AI_API_TOKEN}`,
    },
  });
  if (!statusResponse.ok) break;
  const statusData = await statusResponse.json();
  if (statusData.status === "completed") {
    taskResult = statusData;
    break;
  }
  attempts++;
}

if (!taskResult) {
  return { message: "Crawl did not complete in time." };
}
console.log(taskResult);
```
</details>

Thank you very much for your work! I love it!❤️
Is it even worth trying to figure out how to deploy on docker with the next major changes?
Greeting

**Comment by unclecode** [comment]
@jasperfue tux for kind words, the new docker, is totally a new design, and you pass your environment variables either in "run" command or in an env files. I am testing it these days and this week will be out. Please try that, then I maintain it closely for couple of weeks for issues people report.
