### ISSUE TITLE
When using docker http request, adding the parameter "only_text": True will cause error: crawl4ai.content_scrapping_strategy.WebScrapingStrategy.scrap() got multiple values ​​for keyword argument 'only_text'"

### ISSUE THREAD

**Issue by chenm1xuexi** [unclecode/crawl4ai#260]
First of all, thank you very much for releasing the latest version 0.3.75. The docker image can finally be used normally. But when I set only_text to True, an error will appear: crawl4ai.content_scrapping_strategy.WebScrapingStrategy.scrap() got multiple values ​​for keyword argument 'only_text'". I don't know which one adds multiple values ​​to only_text. I hope it can be fixed.

**Comment by chenm1xuexi** [comment]
Maybe I know the reason for the problem.
The error occurs in  "crawl4ai.async_webcrawler.AsyncWebCrawler.aprocess_html"

only_text is set in **kwargs, but aprocess_html also sets it once, which triggers the problem

![image](https://github.com/user-attachments/assets/3efda8da-6b4a-4126-a9c2-438206fa7833)

**Comment by unclecode** [comment]
@chenm1xuexi Thanks for using the library. This is already fixed in the pull request and merged to the main branch. Please try it again. Thank you.
