### ISSUE TITLE
verbose=False doesn't remove logging?

### ISSUE THREAD

**Issue by vincent0426** [unclecode/crawl4ai#264]
Could we disable these logging while verbose=False?
https://github.com/unclecode/crawl4ai/blob/38044d4afe16b48783457e5ec8538e0a7592e16b/crawl4ai/async_webcrawler.py#L50
https://github.com/unclecode/crawl4ai/blob/38044d4afe16b48783457e5ec8538e0a7592e16b/crawl4ai/async_webcrawler.py#L142

Thanks!

```python
async with AsyncWebCrawler(verbose=False) as crawler:
    result = await crawler.arun(
        url="dummy_url"
    )
    print("Result: ", result)
```
output:
[LOG] 🚀 Crawl4AI 0.3.731
[LOG] 🚀 Content extracted for dummy_url, success: True, time taken: 0.02 seconds
[LOG] 🚀 Extraction done for dummy_url, time taken: 0.02 seconds.

**Comment by unclecode** [comment]
@vincent0426 Thanks for the suggestion, and actually in the new version we have a very advanced, much better logging manager instead of the print; we have a logger class which saves the logs in a file, and if you set verbosity to false, all these logs, including the one that you mentioned, will be gone, so please pull the new version 0.3.74 by today or tomorrow.

**Comment by SCantergiani** [comment]
@unclecode I'm having the same issue on version 7.1

**Comment by unclecode** [comment]
@SCantergiani hi 👋 do u mean although you set verbose to False, it still print logs? Anyway I check it soon 🤔 @ntohidi

**Comment by SCantergiani** [comment]
> [@SCantergiani](https://github.com/SCantergiani) hi 👋 do u mean although you set verbose to False, it still print logs? Anyway I check it soon 🤔 [@ntohidi](https://github.com/ntohidi)

In my case are these, even I have verbose=False

<img width="130" height="192" alt="Image" src="https://github.com/user-attachments/assets/b819d48f-9a8b-42b6-8073-fa1168a0e5d8" />

**Comment by anuragphadke** [comment]
any pointers for the above? still see the INIT and other messages in logs.

**Comment by devknowscode** [comment]
> any pointers for the above? still see the INIT and other messages in logs.

You can use browser and crawl config to hide it like this
```
from crawl4ai import AsyncWebCrawler, BrowserConfig, CrawlerRunConfig

# ...
browser_config = BrowserConfig(
    verbose=False,
)
run_config = CrawlerRunConfig(
    verbose=False,
    log_console=False,
)
async with AsyncWebCrawler(config=browser_config) as crawler:  # config here
    result = await crawler.arun(
        url,
        run_config,  # and here
    )
# ...
```

**Comment by SCantergiani** [comment]
> > any pointers for the above? still see the INIT and other messages in logs.
> 
> You can use browser and crawl config to hide it like this
> 
> ```
> from crawl4ai import AsyncWebCrawler, BrowserConfig, CrawlerRunConfig
> 
> # ...
> browser_config = BrowserConfig(
>     verbose=False,
> )
> run_config = CrawlerRunConfig(
>     verbose=False,
>     log_console=False,
> )
> async with AsyncWebCrawler(config=browser_config) as crawler:  # config here
>     result = await crawler.arun(
>         url,
>         run_config,  # and here
>     )
> # ...
> ```

This worked. Thanks
