### ISSUE TITLE
How to download image?

### ISSUE THREAD

**Issue by xxxspy** [unclecode/crawl4ai#265]
Based on my understanding of craw4ai, it seems there's no direct way to download images using Playwright. Do I have to make a new request? That seems like redundant work.

**Comment by unclecode** [comment]
@xxxspy Thx for trying our library. Crawl4ai returns links to internal and external images, along with relevance scores and textual information. You can then handle downloading the images yourself and use the textual information for applications like information retrieval or image classification. We prioritize generating links to images quickly, and downloading can be done separately using a custom implementation.

However, I think it's a good idea to add an optimized downloader to our library, which could offer parameters for output resolution size. This is a useful suggestion, and I'll consider adding it to our backlog. Thx for the suggestion
