### ISSUE TITLE
Execution context was destroyed, most likely because of a navigation

### ISSUE THREAD

**Issue by Olliejp** [unclecode/crawl4ai#266]
That you for releasing this awesome library!

One issue that I get occasionally is the following:

[ERROR] 🚫 arun(): Failed to crawl https://piworks.net/, error: [ERROR] 🚫 crawl(): Failed to crawl https://piworks.net/: Page.evaluate: Execution context was destroyed, most likely because of a navigation

I am struggling to diagnose the exact route cause of the problem. I was wondering if you had any ideas? Here is my code, thank you. 

```
async def scrape_landing_page(url: str) -> str:
    async with AsyncWebCrawler(verbose=False) as crawler:
        result = await crawler.arun(
            url=url,
            magic=True,
            wait_until='networkidle0',
            remove_overlay_elements=True,
            js_code=[
                "document.querySelector('.cookie-accept')?.click();",
                "window.scrollTo(0, document.body.scrollHeight);",
                """
                var loadMoreButton = document.querySelector('.load-more');
                if (loadMoreButton) {
                    loadMoreButton.click();
                }
                """
            ]
        )
        return result
```

**Comment by unclecode** [comment]
@Olliejp Thanks for using our library. Please try the new version, which I'm going to release today or tomorrow, 0.3.74, because when I tried the link that you gave me, everything works well. And as a side note, by default, the library will scroll to the bottom of the page so you don't need to do that. And another thing that we are working on is handling cookies and banners intelligently in the library. I will update more about it.

```python
async def main():
    async with AsyncWebCrawler(
            headless=True,  # Set to False to see what is happening
            verbose=True,
            sleep_on_close = True,
    ) as crawler:
        result = await crawler.arun(
            url="https://piworks.net/",
            cache_mode=CacheMode.BYPASS,
            remove_overlay_elements=True,
        )
        print(len(result.markdown))

if __name__ == "__main__":
    asyncio.run(main())
```

Output:
```sh
[INIT].... → Crawl4AI 0.3.74
[FETCH]... ↓ https://piworks.net/... | Status: True | Time: 4.38s
[SCRAPE].. ◆ Processed https://piworks.net/... | Time: 158ms
[COMPLETE] ● https://piworks.net/... | Status: True | Total: 4.60s
18657
```
