### ISSUE TITLE
Bubble up errors into responses

### ISSUE THREAD

**Issue by FractalMind** [unclecode/crawl4ai#27]
When you create a request with this URL as example ` https://www.sdfdfhfdsghdfgh` I get a logged error:
`net::ERR_NAME_NOT_RESOLVED`

> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
>     result = await app(  # type: ignore[func-returns-value]
>   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
>     return await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
>     await super().__call__(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
>     raise exc
>   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
>     await self.app(scope, receive, _send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
>     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
>     raise exc
>   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
>     await app(scope, receive, sender)
>   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
>     await route.handle(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
>     await self.app(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
>     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
>   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
>     raise exc
>   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
>     await app(scope, receive, sender)
>   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
>     response = await func(request)
>   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
>     raw_response = await run_endpoint_function(
>   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
>     return await dependant.call(**values)
>   File "/usr/src/app/main.py", line 144, in crawl_urls
>     results = await asyncio.gather(*futures)
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/src/app/crawl4ai/web_crawler.py", line 159, in run
>     html = self.crawler_strategy.crawl(url)
>   File "/usr/src/app/crawl4ai/crawler_strategy.py", line 217, in crawl
>     raise Exception(f"Failed to crawl {url}: {str(e)}")
> Exception: Failed to crawl https://www.sdfdfhfdsghdfgh: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
>   (Session info: chrome-headless-shell=126.0.6478.114)

But the raw response I receive is:

```
StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Tue, 25 Jun 2024 23:53:17 GMT
  Server: uvicorn
  Content-Length: 21
  Content-Type: text/plain; charset=utf-8
}
```

And this is with any kind of error. I'm wondering if there's a way to retrieve the error message/type in the response. So we can process it accordingly. 

Use case: If I enter a wrong URL I want to be able to tell if the URL is valid or not. And treat other errors the right way.

Thank you so much for your time :)

**Comment by unclecode** [comment]
@FractalMind So good you reminded me of this. It has been there since the beginning; I just never documented or mentioned it 😅 and forgot to fill its value in the exception clause. Today, I'll push the new version and make sure it's included.

This is the CrawlResult, you can always check the "success" field and if its false then check the error_message
![image](https://github.com/unclecode/crawl4ai/assets/12494079/b56963f3-869d-4037-8a25-73cb3a15cc88)

**Comment by FractalMind** [comment]
I confirm, it works in the new update

```
{
  "results": [
    {
      "url": "https://ghjfghjfghj",
      "html": null,
      "success": false,
      "cleaned_html": null,
      "media": {},
      "links": {},
      "screenshot": null,
      "markdown": null,
      "extracted_content": null,
      "metadata": null,
      "error_message": "Failed to crawl https://ghjfghjfghj: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome-headless-shell\u003d126.0.6478.126)"
    }
  ]
}
```
