### ISSUE TITLE
Handling pagination/multiple instances of "Load More" button without having to define range of pages to go through.

### ISSUE THREAD

**Issue by sulli365** [unclecode/crawl4ai#292]
Hey, I'm still learning to code so I don't know the full etiquette for posting these types of issues so please let me know if there's more info needed/clarifying questions.

I am trying to scrape the company names from the following venture capital company's website (https://www.breakthroughenergy.org/lookbook/).

The site has a "Load More" button that appears at the bottom, but you need to hit it like ~5 times to actually show all the companies.

I think I could set up a script like the one in the docs that defines a specific number of times to do this action using range(), but I plan on trying to scrape lots of different sites and I was hoping to implement a solution that doesn't require as much manual input to define

I also don't know Javascript, and I know even less of how Javascript is handled within the crawler in terms of its ability to pass info from JS back to the python code that is running.

I've been trying to write Javascript code that is able to:
- determine whether the "Load More" button is present
- If it is, press it and then maybe wait for stuff to load
- If it's no longer present, proceed to scraping all the content.

Here is the code that I've been testing (with lots of different JS code snippets commented out as I try them):

---------------------------
import re
import asyncio
from crawl4ai import AsyncWebCrawler

async def crawl_with_load_more():
    url = "https://www.breakthroughenergy.org/lookbook/"

    js_steps = [
        '''
        function wait(ms) {
            const start = Date.now();
            while (Date.now() - start < ms) {
            // Busy-wait loop
        }

        while (true) {
        // Identify the "Load More" button
            window.scrollTo(0, document.body.scrollHeight);
            const loadMoreButton = document.querySelector('.load-more'); // Replace with the actual selector for your button
        
            if (!loadMoreButton) {
                console.log("No 'Load More' button found. Exiting the loop.");
                break; // Exit the loop if the button doesn't exist
            }

            console.log("Found 'Load More' button. Clicking it...");
            loadMoreButton.click(); // Click the button

            console.log("Waiting for 2 seconds...");
            wait(2000); // Synchronous 2-second pause
        }
    '''
    ]

# doesnt work
    # js_steps = [
    #             '''
    #             try {
    #                 window.scrollTo(0, document.body.scrollHeight);
    #                 const loadMore = document.querySelector('a.load-more');
    #                 if (loadMore) loadMore.click();
    #             } catch {
    #                 console.log('No load more button found');
    #             }
    #             ''' 
    #         ]

  
    # from https://crawl4ai.com/mkdocs/tutorial/episode_05_JavaScript_Execution_and_Dynamic_Content_Handling/
    
    # js_steps = [
    #     "window.scrollTo(0, document.body.scrollHeight);",
    #     "const loadMore = document.querySelector('.load-more'); if (loadMore) loadMore.click();"
    # ]
    # wait_for="js:() => document.querySelectorAll('.item').length > 10"  # Wait until 10 items are loaded

    # from Crawl4ai GPT assistant
    # js_steps = [
    #             "window.scrollTo(0, document.body.scrollHeight);",  # Scroll to the bottom
    #             f"""
    #             const loadMoreButton = document.querySelector('a.load-more');
    #             if (loadMoreButton) {{
    #                 console.log('Load More button clicked.');
    #                 console.log('Load More button attributes:', loadMoreButton.outerHTML);
    #                 loadMoreButton.click();
    #             }} else {{
    #                 console.log('No more Load More button found.');
    #             }}
    #             """
    # ]  
    
    async with AsyncWebCrawler(headless=True, verbose=True) as crawler:
        # load_more_selector = ".load-more"  # Confirm this matches the correct CSS selector for the "Load More" button
        # company_card_selector = ".company-card"  # Selector for loaded content (update as needed)
        # has_more = True
        session_id = "breakthrough_scraping"

        # while has_more:
        print("Scrolling and attempting to load more content...")

        # Scroll to the bottom and click the "Load More" button
        result = await crawler.arun(
            url= url,  #"https://www.breakthroughenergy.org/lookbook/",
            session_id = session_id,
            js_code=js_steps,
            # wait_for="js:() => document.querySelectorAll('.item').length > previousCount",
            # wait_for = "css:.load-more",
            # wait_for="js:() => document.querySelectorAll('.item').length > 10",  # Wait until 10 items are loaded,
            delay_before_return_html=2.0,  # Wait for new content to load
            bypass_cache=True,
            magic=True,
            # word_count_threshold=10,
        )

        print(result.fit_markdown)
    
    # Clean up when done
    await crawler.crawler_strategy.kill_session(session_id)

asyncio.run(crawl_with_load_more())
------------------

In terms of output, it seems like the script is able to hit the "Load More" button once but only that one time. The markdown is returned but not with the whole list of companies, just the ones that become visible after hitting the button once.

I've spent hours digging into Javascript/CSS stuff to try and resolve this on my own but I'm giving up and asking the community, lol.

Is there a way to implement this without having to do pagination?

Relatedly (but out of scope for this question), is anyone aware of a tool (LLM I guess) that can reliably generate page-specific Javascript code based on natural language instructions ("I want to you to look at this page and write Javascript code that will expose all the company names") so that it could be implemented as part of a larger pipeline that could handle many URLs?

Thanks!
Sean

**Comment by unclecode** [comment]
@sulli365 Thx for using Crawl4ai. There's no need to worry. Any question is most welcome. For this kind of crawling, you definitely need to play around a little bit with JavaScript because this sort of data generation is happening dynamically. And this must be triggered dynamically. The most common way we can trigger it is by using JavaScript. There are some other advanced ways to dig in and see how the client-side communicates with the back-end, but that is not the topic of the conversation here. What I suggest is that you improve the quality of your JavaScript and then run it properly. For this particular example, I created the code for you, so I hope this code can be a source of a guideline for other similar crawling experiences. Make sure you have updated your library `pip install -U crawl4ai`.

```python
import asyncio
from crawl4ai import AsyncWebCrawler, CacheMode
from crawl4ai.extraction_strategy import JsonCssExtractionStrategy
import json

async def main():
    schema = {
        "name": "Breakthrough Energy Companies",
        "baseSelector": "tr.logo-parent",
        "fields": [
            {
                "name": "company_name",
                "selector": "th.name span.title",
                "type": "text",
            },
            {
                "name": "company_extra",
                "selector": "th.name span.extra",
                "type": "text", 
            },
            {
                "name": "description",
                "selector": "td.description",
                "type": "text",
            },
            {
                "name": "sector",
                "selector": "td.detail-1 span[role='tooltip']",
                "type": "text",
            },
            {
                "name": "program",
                "selector": "td.detail-2",
                "type": "text",
            },
            {
                "name": "technology", 
                "selector": "td.detail-3",
                "type": "text",
            },
            {
                "name": "logo_url",
                "selector": "th.name img.logo",
                "type": "attribute",
                "attribute": "src"
            }
        ],
    }

    extraction_strategy = JsonCssExtractionStrategy(schema, verbose=True)

    async with AsyncWebCrawler(
        headless=False,
        verbose=True
    ) as crawler:
        
        # Create the JavaScript that handles clicking multiple times
        js_click_load = """
        (async () => {
            for(let i = 0; i < 6; i++) {
                const loadButton = document.querySelector('.load-more');
                if (!loadButton) {
                    console.log('No more load button found');
                    break;
                }
                
                loadButton.scrollIntoView();
                loadButton.click();
                await new Promise(r => setTimeout(r, 1000));
            }
        })();
        """        

        result = await crawler.arun(
            url="https://www.breakthroughenergy.org/lookbook/",
            extraction_strategy=extraction_strategy,
            cache_mode=CacheMode.BYPASS,
            js_code=js_click_load,
        )

        companies = json.loads(result.extracted_content)
        print(f"Successfully extracted {len(companies)} companies")
         
        # Print the first item
        print(json.dumps(companies[0], indent=2))


if __name__ == "__main__":
    asyncio.run(main())
```

You should see something like this:
```bash
[INIT].... → Crawl4AI 0.3.743
[FETCH]... ↓ https://www.breakthroughenergy.org/lookbook/... | Status: True | Time: 6.80s
[SCRAPE].. ◆ Processed https://www.breakthroughenergy.org/lookbook/... | Time: 525ms
[EXTRACT]. ■ Completed for https://www.breakthroughenergy.org/lookbook/... | Time: 0.6484024170204066s
[COMPLETE] ● https://www.breakthroughenergy.org/lookbook/... | Status: True | Total: 8.22s
Successfully extracted 161 companies
{
  "company_name": "44.01",
  "company_extra": "CO2 to X",
  "description": "Offering permanent CO2storage solutions using the natural power of mineralization",
  "sector": "Manufacturing",
  "program": "Ventures",
  "technology": "CO2 to X",
  "logo_url": "https://www.breakthroughenergy.org/wp-content/uploads/2024/06/4401-White.svg"
}
```

**Comment by sulli365** [comment]
Thank you so much for getting back to me! The code works perfectly.

I hadn't even gotten to setting the appropriate extraction scheme yet as I was still trying to figure out the Javascript component, thx for including that!

Looking at your code, it seems like I was mostly on the right track and I just need to develop a better understanding of Javascript and HTML/CSS to better understand how to do the dynamic actions and targeted extractions I need. Skill issue.

One question with this that might require an answer from you - when the crawler is running, how should I think about how the JS code is being run? Is it basically like the crawler is on the webpage, it opens the console, copies and pastes the code from the js_code parameter in the Python code, and clicks execute?

I also noticed/remembered that your roadmap includes things like implementing natural language querying for setting Javascript/extraction schemas. Actually, a bunch of the planned features outlined in the roadmap are very attractive/exciting - that was one of the things that made me feel it was worth investing the time in digging into the library to learn more and try to use it.

Great work, excited to keep using this library!

**Comment by unclecode** [comment]
Thank you for your feedback, and I'm very happy that the code is providing the answers to your earlier questions. And regarding your question and referring to the roadmap, we plan to add JavaScript code generation capabilities to the library next year, using a fine-tuned small language model optimized for data extraction and crawling. This will generate targeted JavaScript code rather than using language models for the entire crawling process. For now, you can write custom JavaScript scripts for different pages. I'll share a link to a detailed discussion on this approach from another issue. There I discussed our roadmap and also shared some of my techniques for deciding how to use JavaScript to reach my objectives within the crawling process. Thank you so much.
