### ISSUE TITLE
Can't handle the reverse crawl?

### ISSUE THREAD

**Issue by zzxtecho** [unclecode/crawl4ai#302]
Can't handle the reverse crawl?
-------------------------------------------------

import asyncio  
from crawl4ai import AsyncWebCrawler, CacheMode  
  
async def main():  
    async with AsyncWebCrawler(verbose=True) as crawler:  
        result = await crawler.arun(url="https://www.baidu.com/")  
        # Soone will be change to result.markdown  
        print(result.markdown_v2.raw_markdown)   
if __name__ == "__main__":  
    asyncio.run(main())  

-----------------------------------------------

[INIT].... → Crawl4AI 0.3.745
[FETCH]... ↓ https://www.baidu.com/... | Status: True | Time: 0.04s
[SCRAPE].. ◆ Processed https://www.baidu.com/... | Time: 1ms        
[COMPLETE] ● https://www.baidu.com/... | Status: True | Total: 0.05s
b17c74766cec61fb

**Comment by unclecode** [comment]
@zzxtecho Would you please add a little bit more explanation about what you mean by the reverse crawl?
