### ISSUE TITLE
Vercel Security Checkpoint

### ISSUE THREAD

**Issue by Erol444** [unclecode/crawl4ai#305]
Hi, 
Thanks for this awesome tool! For most of the websites this tool works great, but for some (based on vercel, example being `stereolabs.com`), extracted markdown in 1/2 of crawled pages is just:
```
We're verifying your browser
Vercel Security Checkpoint
|
sin1::EOJs8k.....
```
I'm using these settings, perhaps there's something better to use? Or some additional delay (seems like 15sec is just skipped?):
```py
    async with AsyncWebCrawler(verbose=False,
                               delay_before_return_html=15.0, # Wait for dynamic content
                               js_code="window.scrollTo(0, document.body.scrollHeight);",
                               wait_for="css:.lazy-content",
                                magic=True,
                                headless=False,
                                simulate_user=True,
                                override_navigator=True,
                                bypass_cache=False,           # Use cache when possible
                                remove_overlay_elements=True,
                               ) as crawler:
```
Any suggestions are welcomed!
Thanks, Erik

**Comment by unclecode** [comment]
@Erol444 Hi Eric, thanks for your kind words. This shows som protection mechanism in the website. Can you give me one of the links that you always get this return? Let me take a look, and find out whats going on.

**Comment by Erol444** [comment]
@unclecode it happens to all of them if you start scrapping with eg. 5sec delay one after another. Perhaps it's required to use proxies anyways?

**Comment by Erol444** [comment]
Another website would be https://pixelscan.net/ - I wanted to check my fingerprints and verify proxy IP, but I get `Crawl4AI Error: This page is not fully supported` every time, even when enabling magic/disabling headless.

**Comment by unclecode** [comment]
@Erol444 Please update to latest version 0.4.0 (I am gonna release it in 8PM Singapore timezone today, 4th Dec). then all will be ok.

```python
import asyncio
from crawl4ai import AsyncWebCrawler, CacheMode

async def main():
    async with AsyncWebCrawler(
            headless=True,  # Set to False to see what is happening
            verbose=True,
            # New feature...
            user_agent_mode="random",
            # Optional...
            user_agent_generator_config={
                "device_type": "mobile",
                "os_type": "android"
            },
    ) as crawler:
        result = await crawler.arun(
            url='https://pixelscan.net/',
            cache_mode=CacheMode.BYPASS,
            html2text = {
                "ignore_links": True
            },
            delay_before_return_html= 2,
            screenshot=True
        )
        
        if result.success:
            print(len(result.markdown_v2.raw_markdown))
            os.system(f"echo '{result.screenshot}' | base64 -d | open -f -a Preview")
   
if __name__ == "__main__":
    asyncio.run(main())
```

Output:
```
[INIT].... → Crawl4AI 0.4.0
[FETCH]... ↓ https://pixelscan.net/... | Status: True | Time: 4.34s
[SCRAPE].. ◆ Processed https://pixelscan.net/... | Time: 41ms
[COMPLETE] ● https://pixelscan.net/... | Status: True | Total: 4.38s
3527
```


![image](https://github.com/user-attachments/assets/e09a634c-bd0f-495f-900b-f296cfc6bcfd)

**Comment by Erol444** [comment]
Amazing! So it just randomizes user agent, and that fixes it?

**Comment by unclecode** [comment]
@Erol444 Yes, randomization will definitely help. My suggestion is to create a high-quality user agent for yourself because different user agents behave differently in various scenarios. For example, sometimes you might want to always appear as a mobile or device user, but not all the time, as pages render differently depending on the device type.  

There are moments when you’ll need a desktop-like user agent, and other times when mimicking a phone device is better for your crawling process. So while randomization is great, having well-crafted user agents is even better.  

Check the documentation (I’ll be updating it soon) for parameters that can help you customize your user agent. Overall, it’s incredible how much you can achieve with a well-designed user agent!
