### ISSUE TITLE
Scraping all sub sections urls from the home page url

### ISSUE THREAD

**Issue by manoj567** [unclecode/crawl4ai#307]
Hi, First of All thank you so much for making crawl4ai opensource . I have one doubt on how to get the content from all sub-urls from the given website url, for example in this [spider](https://spider.cloud/) lets say if i want to automatically get the content from all the sub pages of api,docs pricing along with main content from the home page, how can i achieve this ?

**Comment by unclecode** [comment]
@manoj567 Sorry for my delay, and thx for trying the Crawl4ai. We are releasing a new module, a scraper that exactly provides what you are looking for; it contains different graph search algorithms for getting an input URL and extracting its entire listed structure. Right now, you have to crawl a page and then implement a queue structure to inject all the extracted internal URLs and then crawl them again with any strategy that you want to have. By the end of this month, we will definitely release the scraper, and then, after that, you can use it. It is designed to be very efficient and fast, and memory-friendly, and as usual, it is open source to help you run a DIY on your machine or your server.

**Comment by unclecode** [comment]
@manoj567 I actually answered a similar question a month ago, and I wrote a good enough simple scraper in one of the issues, but I tried to find it and I couldn't; maybe you can search and find it, which was good enough to start. Anyway, as I said, by the end of the month when we release this one, our scraper will cover whatever you may need and more than those paid services they provide, and it also comes with a lot of customization that you can define what you need and what you don't need. So, please stay tuned till we get ready, and we will create good examples and support to ensure it works properly.

**Comment by ajinkyaT** [comment]
@unclecode Any update on the scraper?

**Comment by unclecode** [comment]
@ajinkyaT It's under review and test, soon, cross fingers

**Comment by wefersmasasana** [comment]
has the scraper released or how is the progress going on I really need this feature.

**Comment by aravindkarnam** [comment]
@wefersmasasana Almost done. Will be released within next week.

**Comment by Atrus619** [comment]
Just starting up a crawling project, and really looking forward to this. What will the release version be?

**Comment by Hnam29** [comment]
Wow, what a helpful feature!

**Comment by aravindkarnam** [comment]
@Atrus619 It's going to be version 0.5. Most likely this upcoming week! 🤞🏼

**Comment by jorgoose** [comment]
Was this implemented? Where can I find details about this scraping strategy in the docs. I have a use case where I have a landing page that has many sub-pages, and want to concurrently scrape all of the subpages rather than scraping them sequentially. Thoughts or input?

**Comment by Qbason** [comment]
+1
