### ISSUE TITLE
support ollama?

### ISSUE THREAD

**Issue by win4r** [unclecode/crawl4ai#31]
support ollama?
https://youtu.be/N8yBqEZvvsU

**Comment by unclecode** [comment]
Yes, simply input "ollama/llama3" as the model name, or any other model you have. Ensure the ollama server is operating on its default port.

**Comment by unclecode** [comment]
I have close this issue; please inform me if you require any additional help.

**Comment by Mahizha-N-S** [comment]
ok for provider i will provide the llama3, i hvae the baseURL of the ollama, in place of api-token what should i give then?
strategy = LLMExtractionStrategy(
                provider="ollama/llama3", 
                api_token=os.getenv('API_KEY'),
                .....)
