### ISSUE TITLE
WebSite with Login authentication?

### ISSUE THREAD

**Issue by amitsethitx** [unclecode/crawl4ai#32]
How does craw4ai handle if page has login authentication ? Then this required to search the page that results the list that to be extracted/scraped .

**Comment by unclecode** [comment]
Please check this example: https://crawl4ai.com/mkdocs/examples/hooks_auth/

**Comment by unclecode** [comment]
I have close this issue; please inform me if you require any additional help.

**Comment by akashlp27** [comment]
Hi @unclecode , nice work, I am unable to get the docs for this example (Website Login Authentication). It would be really helpfull if you can provide the same.
