### ISSUE TITLE
AsyncWebCrawler is not re-using localstorage

### ISSUE THREAD

**Issue by Jevli** [unclecode/crawl4ai#322]
It look like when using AsyncPlaywrightCrawlerStrategy with AsyncWebCrawler actions what are done in on_browser_created hook doesn't follow to crawler.arun. And I mean browser localstorage. 

I found website which store token and refreshToken to browser localstorage when log in to page. But when I'm configuring on_browser_created hook to take care of log in AsyncWebCrawler doesn't reuse localstorage. 

I follow code to async_crawler_strategy.py and it seems that when accessing context in use_persistent_context only Browser is collected and not Browser context from Browser.contexts list. Also I didn't find out how to tell strategy to use hole context. 

Is here oversight that you can't reuse localstorage (from on_browser_created hook)? Or might here be bug/missing feauture?

I can't find way to give storageState to crawler strategy or crawler so it could use cookie/localstorage cache from there?

**Comment by Jevli** [comment]
If I use: `use_persistent_context = True`, I get error: `× 'Browser' object has no attribute 'add_init_script'`,

which kind make sense because: https://github.com/unclecode/crawl4ai/blob/ded554d3345ca00c038274fc38ff43b28b45cdd8/crawl4ai/async_crawler_strategy.py#L803

Thought I'm not sure if this is even right way to use it.

**Comment by unclecode** [comment]
@Jevli Such a good question. I think this is an important question, and it will be useful for other future users. So what I do is I provide a very detailed explanation to be used for future reference. In the new version 0.4.2 (Will be released in 1 or 2 days) there is a `storage_state` can be passed to `AsyncWebCrawler`, which allows reusing cookies and localStorage across sessions. The `storage_state` parameter can be a path to a JSON file or a dictionary containing the storage state (cookies, localStorage) that Playwright contexts can use to persist and restore session data. If you load that `storage_state` into the crawler when you start it, subsequent runs and pages will use the previously stored data.

Below is an example of how you could use `storage_state` and `on_browser_created` hook together. In this example, we do a login flow in `on_browser_created` once, export the resulting storage state (which includes localStorage and cookies), and then reuse it in subsequent sessions:

```python
import os, sys
import asyncio
from crawl4ai import AsyncWebCrawler, CacheMode
from crawl4ai.markdown_generation_strategy import DefaultMarkdownGenerator

async def on_browser_created_hook(browser):
    # Suppose we have a login URL and credentials
    # This hook runs once when the browser is first created.
    context = browser.contexts[0]
    page = await context.new_page()
    await page.goto("https://example.com/login", wait_until="domcontentloaded")

    # Perform login steps
    await page.fill("input[name='username']", "myuser")
    await page.fill("input[name='password']", "mypassword")
    await page.click("button[type='submit']")
    await page.wait_for_load_state("networkidle")

    # After login, the website stores tokens in localStorage.
    # Export the storage state so we can reuse it next time
    await context.storage_state(path="my_storage_state.json")
    await page.close()

async def main():
    # First run: perform login and store storage_state
    async with AsyncWebCrawler(
        headless=True,
        verbose=True,
        # The hook will log you in and export the storage state file
        hooks={"on_browser_created": on_browser_created_hook},
        # Use persistent context or managed browser to keep state between runs
        use_persistent_context=True,
        user_data_dir="./my_user_data"
    ) as crawler:
        result = await crawler.arun(
            url='https://example.com/protected-page',
            cache_mode=CacheMode.BYPASS,
            markdown_generator=DefaultMarkdownGenerator(options={"ignore_links": True}),
        )
        print("First run result success:", result.success)
        if result.success:
            print("Protected page HTML length:", len(result.html))

    # Second run: now that we have "my_storage_state.json" with cookies and localStorage
    # we can pass it in storage_state to reuse the login session without hooking again.
    async with AsyncWebCrawler(
        headless=True,
        verbose=True,
        use_persistent_context=True,
        user_data_dir="./my_user_data",
        storage_state="my_storage_state.json"  # Reuse previously exported state
    ) as crawler:
        result = await crawler.arun(
            url='https://example.com/protected-page',
            cache_mode=CacheMode.BYPASS,
            markdown_generator=DefaultMarkdownGenerator(options={"ignore_links": True}),
        )
        print("Second run result success:", result.success)
        if result.success:
            print("Protected page HTML length:", len(result.html))

if __name__ == "__main__":
    asyncio.run(main())
```

**Explanation:**
- In the first run, `on_browser_created_hook` logs into the site and exports the resulting `storage_state` to a file (`my_storage_state.json`).
- On the second run, we pass `storage_state="my_storage_state.json"` directly to the crawler's constructor. Since this state includes cookies and localStorage, the crawler should already be logged in, and you can access protected pages without relogging.

This approach preserves localStorage between sessions and subsequent calls, ensuring that the on-browser-created actions (like login) persist.

And one more thing. You can provide `storage_state` as either a path to a JSON file with this structure, or a Python dictionary matching the same format. The structure Playwright expects looks like this:

```json
{
  "cookies": [
    {
      "name": "session",
      "value": "abcd1234",
      "domain": "example.com",
      "path": "/",
      "expires": 1675363572.037711,
      "httpOnly": false,
      "secure": false,
      "sameSite": "None"
    }
  ],
  "origins": [
    {
      "origin": "https://example.com",
      "localStorage": [
        { "name": "token", "value": "my_auth_token" },
        { "name": "refreshToken", "value": "my_refresh_token" }
      ]
    }
  ]
}
```

**Example as a JSON File:**  
Save the above snippet into a file named `mystate.json`. Then pass it to your crawler like:
```python
async with AsyncWebCrawler(
    headless=True,
    storage_state="mystate.json",
    ...
) as crawler:
    ...
```

**Example as a Python Dictionary (No File Needed):**  
You can define the same structure directly in Python and pass it as a dictionary:
```python
storage_dict = {
    "cookies": [
        {
            "name": "session",
            "value": "abcd1234",
            "domain": "example.com",
            "path": "/",
            "expires": 1675363572.037711,
            "httpOnly": False,
            "secure": False,
            "sameSite": "None"
        }
    ],
    "origins": [
        {
            "origin": "https://example.com",
            "localStorage": [
                {"name": "token", "value": "my_auth_token"},
                {"name": "refreshToken", "value": "my_refresh_token"}
            ]
        }
    ]
}

async with AsyncWebCrawler(
    headless=True,
    storage_state=storage_dict,  # Passing dictionary directly
    ...
) as crawler:
    ...
```

This way, you can pre-define cookies and localStorage entries you want Playwright to have before navigating to pages, effectively simulating a logged-in state or any other precondition without having to run a login flow first.

**Comment by unclecode** [comment]
> If I use: `use_persistent_context = True`, I get error: `× 'Browser' object has no attribute 'add_init_script'`,
> 
> which kind make sense because:
> 
> https://github.com/unclecode/crawl4ai/blob/ded554d3345ca00c038274fc38ff43b28b45cdd8/crawl4ai/async_crawler_strategy.py#L803
> 
> Thought I'm not sure if this is even right way to use it.

Can you share with me your code snippet? I need to replicate the error. Anyway try this again on the new version. Thx

**Comment by Jevli** [comment]
> > If I use: `use_persistent_context = True`, I get error: `× 'Browser' object has no attribute 'add_init_script'`,
> > which kind make sense because:
> > https://github.com/unclecode/crawl4ai/blob/ded554d3345ca00c038274fc38ff43b28b45cdd8/crawl4ai/async_crawler_strategy.py#L803
> > 
> > Thought I'm not sure if this is even right way to use it.
> 
> Can you share with me your code snippet? I need to replicate the error. Anyway try this again on the new version. Thx

I can't repeat this now... If I get this again I will post snippet. 

Though thanks to answer for first question.

**Comment by unclecode** [comment]
@Jevli 0.4.2 is almost ready and will be out soon, I will send update on my X.

**Comment by Jevli** [comment]
@unclecode I think this can be closed now. Got local storage in use with your changes. Thank you so much for this project!

**Comment by unclecode** [comment]
You're welcome

**Comment by redron** [comment]
I'll just share my findings. This parameter didn't work for me as well when I used it the following way:

```python

    async with AsyncWebCrawler(verbose=True,
                               crawler_strategy=crawler_strategy,
                               use_persistent_context=True,
                               storage_state="my_storage_state.json"                        
```
    
because AsyncWebCrawler seems to completely ignore the `storage_state` parameter...
    
But I was able to make it work by adding this parameter to the config of `AsyncPlaywrightCrawlerStrategy`
    
    
```python
browser_config: BrowserConfig = BrowserConfig(verbose=True,
                                              headless=True,
                                              storage_state="my_storage_state.json")
                                                                          
crawler_strategy = AsyncPlaywrightCrawlerStrategy(browser_config=browser_config)
```

**Comment by unclecode** [comment]
@redron I will take a quick look to ensure it still works, although I am trying to move everybody to use this new approach, and maintaining compatibility with the previous version may cause issues. Thx for mentioning this.

**Comment by mikurisan** [comment]
> [@redron](https://github.com/redron) I will take a quick look to ensure it still works, although I am trying to move everybody to use this new approach, and maintaining compatibility with the previous version may cause issues. Thx for mentioning this.我会快速检查一下以确保它仍然可用，尽管我正尝试让所有人改用这种新方法，并且为了兼容之前的版本可能会导致问题。谢谢你提到这一点。

Hi, any updates? Storage state still can't working according this [tutorial](https://github.com/unclecode/crawl4ai/blob/main/docs/examples/storage_state_tutorial.md).

params `storage_state` and `use_persistent_context` are not in class `AsyncWebCrawler`, they only show in class `BrowserConfig`.

So I change to use my version:

```python
    browser_config = BrowserConfig(
        use_persistent_context=True,
        storage_state="./my_storage.json",
        headless=False
    )

	crawler = AsyncWebCrawler(config=browser_config)
```

Error occurred:

```
[ERROR]... × https://xxx.a.c...ite/#/infoCenter/search  | Error: Unexpected error in _crawl_web at line 536 in clone_runtime_state 
(D:\software\miniconda3\envs\crawler\Lib\site-packages\crawl4ai\browser_manager.py):
Error: Page.evaluate() takes from 2 to 3 positional arguments but 4 were given

Code context:
 531               continue
 532   
 533           page = dst.pages[0] if dst.pages else await dst.new_page()
 534           await page.goto(url, wait_until="domcontentloaded")
 535           for k, v in kvs:
 536 →             await page.evaluate("(k,v)=>localStorage.setItem(k,v)", k, v)
 537   
 538       # ── 3. runtime-mutable extras from configs ────────────────────────────────
 539       # headers
 540       if browserConfig and browserConfig.headers:
 541           await dst.set_extra_http_headers(browserConfig.headers) 

Unexpected error in _crawl_web at line 536 in clone_runtime_state (D:\software\miniconda3\envs\crawler\Lib\site-packages\crawl4ai\browser_manager.py):
Error: Page.evaluate() takes from 2 to 3 positional arguments but 4 were given

Code context:
 531               continue
 532
 533           page = dst.pages[0] if dst.pages else await dst.new_page()
 534           await page.goto(url, wait_until="domcontentloaded")
 535           for k, v in kvs:
 536 →             await page.evaluate("(k,v)=>localStorage.setItem(k,v)", k, v)
 537
 538       # ── 3. runtime-mutable extras from configs ────────────────────────────────
 539       # headers
 540       if browserConfig and browserConfig.headers:
 541           await dst.set_extra_http_headers(browserConfig.headers)
```
