### ISSUE TITLE
Installation Error due to setup.py Encoding Issue

### ISSUE THREAD

**Issue by waldyhester** [unclecode/crawl4ai#35]
I encountered an issue when trying to install the project using the standard instructions provided in the README. The installation process failed with an error.

**Steps to Reproduce:**
1. Clone the repository.
2. Run `python setup.py install`.

**Observed Behavior:**
The installation fails with an error related to reading the `README.md` file.

**Expected Behavior:**
The installation should complete successfully.

**Solution:**
I modified the `setup.py` file to fix this issue. Specifically, I changed the line:

```python
long_description=open("README.md").read(),
```

to

```python
long_description=open("README.md", encoding="utf-8").read(),
```

After making this change, the installation worked correctly.

Questions:

Should I create a pull request with this change?
Did I do something wrong or miss an existing solution to this issue?

**Comment by HoKei2001** [comment]
Same Issue, your solution helps :-)

**Comment by unclecode** [comment]
@waldyhester Appreciate your PR request, please go ahead, by all means.

**Comment by unclecode** [comment]
@waldyhester Apologies, I've observed that another community member has already created a pull request, so I have merged that one. Nevertheless, I appreciate the support.
