### ISSUE TITLE
[QUESTION] excluded_tags support for arun_many()

### ISSUE THREAD

**Issue by gamelogai** [unclecode/crawl4ai#351]
First of all - thank you! It is an amazing product.

I was looking into `arun_many()` https://github.com/unclecode/crawl4ai/blob/ed7bc1909cdd49e23bc665d746f60a0b2fcaf594/crawl4ai/async_webcrawler.py#L525 and noticed it has many args deprecated and mostly managed via CrawlerRunConfig https://github.com/unclecode/crawl4ai/blob/ed7bc1909cdd49e23bc665d746f60a0b2fcaf594/crawl4ai/async_configs.py#L175 and unlike `arun()` it has no support of `excluded_tags` which is extremely useful. 

Can you please tell me if I happened to overlook some other place I can use it with or `excluded_tags` isn't supported with `arun_many()`. If it isn't supported, is there a plan to add it by any chance? 

Thank you

**Comment by gamelogai** [comment]
Apologies, I found it is managed by 
https://github.com/unclecode/crawl4ai/blob/ed7bc1909cdd49e23bc665d746f60a0b2fcaf594/crawl4ai/content_filter_strategy.py#L22

Closing

**Comment by unclecode** [comment]
@gamelogai  You are very right, I actually missed it. By the way, right now, it still you can pass as keyword arguments. It works as before. I updated and I will put it in the next release, which I'm going to put it by today or tomorrow.
