### ISSUE TITLE
[Enhancement] Asyncrawl needs to obtain an SSL certificate

### ISSUE THREAD

**Issue by wakaka6** [unclecode/crawl4ai#368]
Thanks for the work you have done, I'm currently building a service for large model identification phishing site detection based on your project. For the accuracy of the detection, when crawling the web page, I would like to get the SSL certificate of the target website.

**Comment by unclecode** [comment]
@wakaka6 Thank you for the suggestions and for managing the backlog. Since you mentioned it, I just updated the library to support version 0.4.24. I will release it in a day or two, and then you will have it. Thank you again for your suggestions, help, and support.
