### ISSUE TITLE
Add Config Parameter to Configure HTML Parser for _scrap Method

### ISSUE THREAD

**Issue by pleomax0730** [unclecode/crawl4ai#380]
The `_scrap` method currently uses `lxml` as the default parser when processing HTML content. However, it has been observed that `lxml` causes the `body` content to lose some information. In contrast, using `html.parser` resolves the issue and retrieves the full content.  
```python
def _scrap(self, url: str, html: str, word_count_threshold: int = MIN_WORD_THRESHOLD, css_selector: str = None, **kwargs) -> Dict[str, Any]:
    success = True
    if not html:
        return None
    soup = BeautifulSoup(html, 'lxml')
    body = soup.body
```
This issue becomes evident when scraping websites like [[Sina Finance](https://vip.stock.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?stockid=300296&id=9962287)], where the `body` tag only contains partial content when parsed with `lxml`.  

**Expected Behavior:**  
The method should allow configuring the parser (e.g., `lxml` or `html.parser`) via a parameter to ensure flexibility and full content retrieval based on the website's structure.  

**Proposed Solution:**  
- Add a parameter (e.g., `parser: str = 'lxml'`) to the `CrawlerRunConfig` to let users choose the desired parser.
- Pass the `parser` parameter to the `BeautifulSoup` constructor.  
- Update the method documentation to reflect this change.  

This enhancement would allow better adaptability and prevent loss of critical content.

**Comment by unclecode** [comment]
@pleomax0730 Thanks for the suggestion. I completely agree. One thing I like about `lxml` is that it is much faster than the HTML parser, especially when crawling long documents. Speed and efficiency are my top priorities for Crawl4ai. Even if something offers a 10-millisecond improvement, I choose that option. And in the case of this parser, the difference is significant. However I completely agree with you; we must have an option. Already modified the library and In the next version 0.4.24, you will have `parser_type` that you can set. You can pass it to `html.parser`, or you can pass nothing; the default will be `lxml`. Thank you so much for the suggestion.
