### ISSUE TITLE
Can I use the function of crawling and cleaning separately?

### ISSUE THREAD

**Issue by LinXin04** [unclecode/crawl4ai#381]
If I have got the content of html of a url, but not used crawl4ai. Then I want to clean the html by using crawl4ai, how can I do.
Because  all examples I see are the combination of crawling and cleaning. As follows：

result = await crawler.arun(url="https://example.com", fit_markdown=True)
print(result.html)         # Raw HTML
print(result.cleaned_html) # Cleaned HTML
print(result.markdown)     # Markdown version
print(result.fit_markdown) # Most relevant content in markdown

**Comment by unclecode** [comment]
@LinXin04 Thx for trying Crawl4ai, Here's how you can process raw HTML content with Crawl4AI:

```python
import asyncio
from crawl4ai import AsyncWebCrawler

async def process_html():
    # Your raw HTML content
    raw_html = """
    <html>
        <body>
            <h1>Hello World</h1>
            <p>This is a test paragraph.</p>
        </body>
    </html>
    """
    
    async with AsyncWebCrawler() as crawler:
        # Use the "raw:" prefix to indicate raw HTML content
        result = await crawler.arun(url=f"raw:{raw_html}")
        
        print("Raw HTML:", result.html)  # Original HTML
        print("Cleaned HTML:", result.cleaned_html)  # Cleaned HTML
        print("Markdown:", result.markdown)  # Markdown version
        print("Fit Markdown:", result.fit_markdown)  # Most relevant content

asyncio.run(process_html())
```

Alternatively, if you have HTML content in a local file:

```python
async def process_html_file():
    async with AsyncWebCrawler() as crawler:
        # Use the "file://" prefix for local HTML files
        result = await crawler.arun(url="file://path/to/your/local/file.html")
        
        print("Raw HTML:", result.html)
        print("Cleaned HTML:", result.cleaned_html)
        print("Markdown:", result.markdown)
        print("Fit Markdown:", result.fit_markdown)

asyncio.run(process_html_file())
```

Key points to note:

1. For raw HTML strings, use the "raw:" prefix
2. For local HTML files, use the "file://" prefix
3. The processing will be done without actually making any HTTP requests
4. All the usual cleaning and conversion features work the same way as with web URLs

This should help you process your existing HTML content through Crawl4AI's cleaning and conversion pipeline without needing to crawl any URLs.

**Comment by aboozaid2** [comment]
> [@LinXin04](https://github.com/LinXin04) Thx for trying Crawl4ai, Here's how you can process raw HTML content with Crawl4AI:
> 
> import asyncio
> from crawl4ai import AsyncWebCrawler
> 
> async def process_html():
>     # Your raw HTML content
>     raw_html = """
>     <html>
>         <body>
>             <h1>Hello World</h1>
>             <p>This is a test paragraph.</p>
>         </body>
>     </html>
>     """
>     
>     async with AsyncWebCrawler() as crawler:
>         # Use the "raw:" prefix to indicate raw HTML content
>         result = await crawler.arun(url=f"raw:{raw_html}")
>         
>         print("Raw HTML:", result.html)  # Original HTML
>         print("Cleaned HTML:", result.cleaned_html)  # Cleaned HTML
>         print("Markdown:", result.markdown)  # Markdown version
>         print("Fit Markdown:", result.fit_markdown)  # Most relevant content
> 
> asyncio.run(process_html())
> Alternatively, if you have HTML content in a local file:
> 
> async def process_html_file():
>     async with AsyncWebCrawler() as crawler:
>         # Use the "file://" prefix for local HTML files
>         result = await crawler.arun(url="file://path/to/your/local/file.html")
>         
>         print("Raw HTML:", result.html)
>         print("Cleaned HTML:", result.cleaned_html)
>         print("Markdown:", result.markdown)
>         print("Fit Markdown:", result.fit_markdown)
> 
> asyncio.run(process_html_file())
> Key points to note:
> 
> 1. For raw HTML strings, use the "raw:" prefix
> 2. For local HTML files, use the "file://" prefix
> 3. The processing will be done without actually making any HTTP requests
> 4. All the usual cleaning and conversion features work the same way as with web URLs
> 
> This should help you process your existing HTML content through Crawl4AI's cleaning and conversion pipeline without needing to crawl any URLs.

This is still force us to install browsers otherwise the code won't run. My use case is to use JsonCssExtraction strategy but I do not need to download full playwright browses I already use camoufox
