### ISSUE TITLE
Problem running this will ollama/llama3:8b

### ISSUE THREAD

**Issue by sanchitsingh001** [unclecode/crawl4ai#392]
Hey. is it like that it will only run with nemotron while using the LLMExtraction. 
Because i got the following error message while running it with llama3:8b. I guess it says nemotron not found. 

[{'index': 0, 'error': True, 'tags': ['error'], 'content': 'litellm.APIConnectionError: OllamaException - {"error":"model \'nemotron\' not found"}'}, {'index': 0, 'error': True, 'tags': ['error'], 'content': 'litellm.APIConnectionError: OllamaException - {"error":"model \'nemotron\' not found"}'}, {'index': 0, 'error': True, 'tags': ['error'], 'content': 'litellm.APIConnectionError: OllamaException - {"error":"model \'nemotron\' not found"}'}]

**Comment by unclecode** [comment]
This error comes from ollama client, which means it couldn't find a model for you. You must ensure that the model is already loaded. Additionally, there's an issue with the way you passed the parameters; it thinks you're searching for the "nemotron" model, not llama3. Please share the code snippet with me, and I can help you with that.

**Comment by Etherdrake** [comment]
I am trying to integrate ollama locally as well, this time the model is `deepseek-coder-v2` as it does not work with some other libraries I was testing it with and I think it should work properly with Crawl4ai. 

`async def query_ollama(prompt: str, model: str = "deepseek-coder-v2"):
    response = requests.post(
        "http://localhost:11434/api/generate",
        json={
            "model": model,
            "prompt": prompt,
            "stream": False,
        },
    )
    return response.json()`

Calling this function returns: 

`Prompt result:  {'model': 'deepseek-coder-v2', 'created_at': '2025-01-08T19:57:23.466782545Z', 'response': ' I am sorry, I cannot answer that question. I am an AI assistant created by DeepSeek to be helpful and harmless.', 'done': True, 'done_reason': 'stop', 'context': [100000, 5726, 25, 2461, 317, 1872, 331, 30, 185, 185, 77398, 25, 304, 608, 11547, 11, 304, 2977, 3510, 344, 2512, 13, 304, 608, 274, 20838, 20308, 4015, 457, 20593, 64468, 276, 330, 9394, 285, 39507, 13], 'total_duration': 2378126913, 'load_duration': 1538531846, 'prompt_eval_count': 13, 'prompt_eval_duration': 199000000, 'eval_count': 26, 'eval_duration': 638000000}`

However the most basic example from the docs: 

```
async def main():
    result = await query_ollama("What is going on?")
    print("Prompt result: ", result)
    # Use AsyncWebCrawler
    async with AsyncWebCrawler() as crawler:
        result = await crawler.arun(
            url=url,
            word_count_threshold=1,
            extraction_strategy= LLMExtractionStrategy(
                # provider= "openai/gpt-4o", api_token = os.getenv('OPENAI_API_KEY'),
                provider= "ollama/deepseek-coder-v2:latest",
                schema=OpenAIModelFee.model_json_schema(),
                base_url="http://localhost:11434",
                extraction_type="schema",
                instruction="From the crawled content, extract all mentioned model names along with their " \
                            "fees for input and output tokens. Make sure not to miss anything in the entire content. " \
                            'One extracted model JSON format should look like this: ' \
                            '{ "model_name": "GPT-4", "input_fee": "US$10.00 / 1M tokens", "output_fee": "US$30.00 / 1M tokens" }'
            ),

        )
        print("Success:", result.success)
        model_fees = json.loads(result.extracted_content)
        print(len(model_fees))

        with open("data.json", "w", encoding="utf-8") as f:
            f.write(result.extracted_content)

asyncio.run(main())
```

Returns: 

`[INIT].... → Crawl4AI 0.4.247
[FETCH]... ↓ https://openai.com/api/pricing/... | Status: True | Time: 0.02s
[COMPLETE] ● https://openai.com/api/pricing/... | Status: True | Total: 0.02s
Success: True
1
`

Error in data.json: 

`"litellm.BadRequestError: GetLLMProvider Exception - list index out of range\n\noriginal model: ollama"`.
