### ISSUE TITLE
Question: How does one crawl for the visible text?

### ISSUE THREAD

**Issue by qualyon** [unclecode/crawl4ai#4]
This is not a bug, but a question on how to use the product.

For this website: https://cgmcafe.org/
You can see that there is a telephone number in the footer. When I crawl, I do not see the number. How do I do that?

Here's the curl I used:
curl -X POST   http://localhost:9333/crawl   -H 'Content-Type: application/json'   -d '{
    "urls": ["https://cgmcafe.org"],
    "include_raw_html": true,
    "bypass_cache": true,
    "word_count_threshold": 5,
    "extraction_strategy": "CosineStrategy",
    "chunking_strategy": "NlpSentenceChunking",
    "css_selector": "p",
    "verbose": true,
    "extraction_strategy_args": {
        "semantic_filter": "purpose of company",
        "word_count_threshold": 20,
        "max_dist": 0.2,
        "linkage_method": "ward",
        "top_k": 3
    }
  }'

**Comment by unclecode** [comment]
Interesting, let me take a look at that 🤔

**Comment by unclecode** [comment]
![image](https://github.com/unclecode/crawl4ai/assets/12494079/6d30c66f-b410-4b2c-8112-4ade457b7511)

I just checked. Simply set the "word_count_threshold" to 1. By default, it's set to 10, so any element with a word count less than 10 will be filtered out.

```py
from crawl4ai.web_crawler import WebCrawler
from crawl4ai.extraction_strategy import *
from crawl4ai.chunking_strategy import *

crawler = WebCrawler()
crawler.warmup()

result = crawler.run(
    url='https://cgmcafe.org/',
    word_count_threshold=1,
    extraction_strategy=NoExtractionStrategy(),
    chunking_strategy=RegexChunking(),
    bypass_cache=true,
    css_selector=""
)
print(result)
```
