### ISSUE TITLE
CSS Selector:  gives error

### ISSUE THREAD

**Issue by merihakca** [unclecode/crawl4ai#43]
When I use below statement to select the text only from div summaryPoints, it gives syntax error. What could be the correct syntax ? Notice the single quote inside the double quotes.

css_selector="div id='summaryPoints' "

[ERROR] 🚫 Failed to crawl https://www.bbc.com/news/live/cn087x77g1dt, error: Invalid character '=' position 6   line 1:
div id='summaryPoints'

**Comment by unclecode** [comment]
@merihakca You should pass W3C CSS selector, try it like this:

`result = crawler.run( url, css_selector="div#summaryPoints")`

You can check this link to know more about this. [CSS SElector](https://www.w3schools.com/cssref/css_selectors.php)

**Comment by merihakca** [comment]
> @merihakca You should pass W3C CSS selector, try it like this:
> 
> `result = crawler.run( url, css_selector="div#summaryPoints")`
> 
> You can check this link to know more about this. [CSS SElector](https://www.w3schools.com/cssref/css_selectors.php)

many thanks
