### ISSUE TITLE
Delay crawling for slow websites

### ISSUE THREAD

**Issue by knandersen** [unclecode/crawl4ai#45]
I am trying to crawl a website, but it takes a while to load, and from my screenshot I can see that by the time the crawler starts, it's still just skeleton content. Is there a way to delay the crawling? I couldn't find it from the documentation, and tried to use the custom `js_code` to implement a function that blocks the main loop:

```
js_code=["const sleep = (ms) => { const start = Date.now(); while(Date.now() - start < ms) {}}; sleep(5000)"]

def create_crawler():
    crawler = WebCrawler(verbose=True)
    crawler.warmup()
    return crawler

crawler = create_crawler()
result = crawler.run(
    url=url, 
    js=js_code,
    screenshot=True,
    chunking_strategy=NlpSentenceChunking()
)
```

But it doesn't seem to have any effect. Anyone else had success with something like this, or could a delay feature be added?

PS: I'm excited about this project, thanks for making it!

**Comment by unclecode** [comment]
@knandersen It is actually supposed to detect such situations. Could you please provide the URL? I can assist you with that.

**Comment by unclecode** [comment]
@knandersen Just to inform you that if you desire a custom time delay before fetching the HTML, you can utilize the "after_get_url" hook. Here's an example:

```python
import time
def create_crawler():
    crawler = WebCrawler(verbose=True)
    crawler.warmup()
    return crawler

crawler = create_crawler()
crawler.set_hook('after_get_url', lambda _: time.sleep(5))
result = crawler.run(url="https://example.com")
```
This instructs the crawler to wait for 5 seconds before attempting to extract the HTML.

**Comment by knandersen** [comment]
@unclecode thanks for the hook trick! I'm trying to find a url I can provide you as an example (unfortunately not allowed to share the one I encountered the problem with)

**Comment by unclecode** [comment]
@knandersen I apologize for my mistake! It's funny that I incorrectly implemented my own code. Kindly refer to this code:

```python
import time

from crawl4ai.web_crawler import WebCrawler
from crawl4ai.crawler_strategy import *

def delay(driver):
    print("Delaying for 5 seconds...")
    time.sleep(5)
    print("Resuming...")
    
def create_crawler():
    crawler_strategy = LocalSeleniumCrawlerStrategy(verbose=True)
    crawler_strategy.set_hook('after_get_url', delay)
    crawler = WebCrawler(verbose=True, crawler_strategy=crawler_strategy)
    crawler.warmup()
    return crawler

crawler = create_crawler()
result = crawler.run(url="https://google.com", bypass_cache=True)
```

**Comment by knandersen** [comment]
this works, thank you so much!
