### ISSUE TITLE
Crawling prints formatted content, how to avoid it ?

### ISSUE THREAD

**Issue by merihakca** [unclecode/crawl4ai#46]
The crawled content is printed in key:value pair as shown below, how can I avoid it ? I want only the text part "Voter turnout in Sunday\\'s poll soared..etc"  as shown below. 

 {
        "index": 7,
        "tags": [],
        "content": "  * Voter turnout in Sunday\\'s poll soared - the highest in a parliamentary election since 1997"
    },

My script as below
from crawl4ai import WebCrawler
from crawl4ai.chunking_strategy import *
from crawl4ai.extraction_strategy import *
from crawl4ai.crawler_strategy import *

def create_crawler():
    crawler = WebCrawler(verbose=True)
    crawler.warmup()
    return crawler

crawler = create_crawler()

result = crawler.run(    url="https://www.bbc.com/news/live/cn087x77g1dt", css_selector="#summaryPoints", verbose = False , only_text=True , word_count_threshold = 30 ,  screenshot = True )

print("Extracted as follows:", result.extracted_content)

**Comment by unclecode** [comment]
@merihakca Consider using `result.markdown` for the complete markdown text. Utilize `extracted_content` in 2 instances: 

1. When employing CosineExtraction or LLMExtraction strategy 
3. When integrating text processing before combining them into a task-appropriate full text.
