### ISSUE TITLE
Error retrieving cached URL: no such column: links

### ISSUE THREAD

**Issue by SuroshAhmadZobair** [unclecode/crawl4ai#49]
Hi 
Thanks for working on this project @unclecode .

When I run your openai pricing example, i get an error retrieving cached url. 
`Error retrieving cached URL: no such column: links
`

I wonder  if this is expected. 

also, every now and then I also get the following error:
`Error extracting blocks: Expecting value: line 1 column 1 (char 0)
`

cheers

**Comment by unclecode** [comment]
@SuroshAhmadZobair You're welcome and Today I released version 0.2.74. Kindly install it, this is already fixed. Additionally, consider removing the ".crawl4ai" directory from your home folder. This step is not mandatory, but it is recommended. For Mac users, the path is "~/.crawl4ai", and for Windows users, it will be "c:\users\%username%\.crawl4ai".
