### ISSUE TITLE
Colab Issue

### ISSUE THREAD

**Issue by caramale07** [unclecode/crawl4ai#5]
There are problems with running in colab. Cannot install the module because of dependency issues

**Comment by unclecode** [comment]
> There are problems with running in colab. Cannot install the module because of dependency issues

I see, could you plz share more details or a screenshot of the error message?

**Comment by caramale07** [comment]
![image](https://github.com/unclecode/crawl4ai/assets/94035234/471bb4fc-76c8-4c7b-9e10-28a361b22b38)
`!pip install "crawl4ai[colab] @ git+https://github.com/unclecode/crawl4ai.git"`

**Comment by unclecode** [comment]
I remove tokenizer version from requirements.txt, would you plz try again.

**Comment by unclecode** [comment]
Try to remove versions from all libraries in requirements.txt, let me know please if that help. Also please share your system details.

**Comment by caramale07** [comment]
Thanks it works now
