### ISSUE TITLE
Question about using proxy in WebCrawler

### ISSUE THREAD

**Issue by xwt1** [unclecode/crawl4ai#52]
Hi,
     I'm currently using WebCrawler to scrape websites, and I need to set a proxy. I've tried using the os.environ method to set a global proxy, Unfortunately, this method did not work as expected. Could you please provide guidance on how to correctly set a proxy for WebCrawler? Any help will be appreciated!
Thank you!

**Comment by unclecode** [comment]
@xwt1 Thx for using the library, let me work on that and will back to you

**Comment by xwt1** [comment]
Thanks for reply! Your amazing work truly help me a lot!
