### ISSUE TITLE
Installation problem on linux

### ISSUE THREAD

**Issue by babazaroni** [unclecode/crawl4ai#53]
On linux, crawl4ai requires aoihttp 3.9.5 but pip will only install 3.8.6.

I am using latest Ubuntu.

**Comment by babazaroni** [comment]
Here is the installation attempt:

(base) cc@cc-Venus-series:~/bebop$ pip install "crawl4ai @ git+https://github.com/unclecode/crawl4ai.git"
Collecting crawl4ai@ git+https://github.com/unclecode/crawl4ai.git
  Cloning https://github.com/unclecode/crawl4ai.git to /tmp/pip-install-f2sx6hsu/crawl4ai_a986832c974d46fa8daa8181eeaa34d3
  Running command git clone -q https://github.com/unclecode/crawl4ai.git /tmp/pip-install-f2sx6hsu/crawl4ai_a986832c974d46fa8daa8181eeaa34d3
ERROR: Could not find a version that satisfies the requirement aiohttp==3.9.5 (from crawl4ai)
ERROR: No matching distribution found for aiohttp==3.9.5

**Comment by unclecode** [comment]
@babazaroni Please remove the version from requirements.txt and reinstall; it actually works with 3.8.6 as well.
