### ISSUE TITLE
Can't use local LLM model

### ISSUE THREAD

**Issue by Chi-chicken** [unclecode/crawl4ai#55]
I'm trying to use crael4ai with local LLM model, but facing some issue. I replace the provider to my local llm port and not knowing what to do with the api_token. Please give me some suggestion, thanks.
`extraction_strategy=LLMExtractionStrategy(
    provider="your_llm_provider/model_name",
    api_token="your_api_token",
    instruction="Your extraction instruction"
)`

**Comment by unclecode** [comment]
Hi @Chi-chicken re you using Ollama for your local machine? Please share more details on your local LLM.

**Comment by Chi-chicken** [comment]
Yes, I'm using a local Ollama/Llama-3:8B model. I'm trying to modify the function`perform_completion_with_backoff` in utils.py to enforce the response with my local llm like this.

``` python
def perform_completion_with_backoff(provider, prompt_with_variables, api_token, json_response = False):
    from litellm import completion 
    from litellm.exceptions import RateLimitError
    max_attempts = 3
    base_delay = 2  # Base delay in seconds, you can adjust this based on your needs
    
    extra_args = {}
    if json_response:
        extra_args["response_format"] = { "type": "json_object" }
    
    for attempt in range(max_attempts):
        try:
            from huggingface_hub import InferenceClient
            client = InferenceClient("my-llm-host")
            response = client.text_generation(prompt_with_variables, **extra_args)
            # response =completion(
            #     model=provider,
            #     messages=[
            #         {"role": "user", "content": prompt_with_variables}
            #     ],
            #     temperature=0.01,
            #     api_key=api_token,
            #     **extra_args
            # )
            return response  # Return the successful response
```
But, when I run the code, I still got error.
``` python
from crawl4ai.web_crawler import WebCrawler
crawler = WebCrawler()
crawler.warmup()
url2 = "https://www.google.com.tw/?hl=zh_TW"
result = crawler.run(
        url=url2,
        extraction_strategy=LLMExtractionStrategy(
            provider="",
            api_token= "-",
            instruction="Extract only content related to PLM"
        ),
    bypass_cache=True,
    markdown=True,
    )
```
```
[LOG] 🚀 Initializing LocalSeleniumCrawlerStrategy
[LOG] 🌤️  Warming up the WebCrawler
[LOG] 🌞 WebCrawler is ready to crawl
[LOG] 🚀 Crawling done for https://www.google.com.tw/?hl=zh_TW, success: True, time taken: 1.6670608520507812 seconds
[LOG] 🚀 Content extracted for https://www.google.com.tw/?hl=zh_TW, success: True, time taken: 0.030132770538330078 seconds
[LOG] 🔥 Extracting semantic blocks for https://www.google.com.tw/?hl=zh_TW, Strategy: LLMExtractionStrategy
[LOG] Call LLM for https://www.google.com.tw/?hl=zh_TW - block index: 0
Error in thread execution: 'str' object has no attribute 'choices'
[LOG] 🚀 Extraction done for https://www.google.com.tw/?hl=zh_TW, time taken: 0.7435650825500488 seconds.
```
Is there any simple methods to use our local model and not calling litellm?

**Comment by unclecode** [comment]
@Chi-chicken, take a look at the code snippet below that I'm currently running on my machine with Ollama:

```
result = crawler.run(
        url=url,
        extraction_strategy=LLMExtractionStrategy(
            provider="ollama/llama3",
            api_token="no-token",
            instruction="Extract only content related to PLM"
        ),
       bypass_cache=True,
)
```

This is executing without any errors. Even though the URL is simply "https://www.google.com.tw/?hl=zh_TW," leading to a Google page with no "PLM" information. My main point is that there's no need to modify `perform_completion_with_backoff` to enforce the use of Ollama. It seems like it already handles this seamlessly. Please let me know if you have other reason to not use Litellm, then I try to provide you with an example.

**Comment by Chi-chicken** [comment]
@unclecode, thank you for your reply. Because of the proxy issue, I can't set `provider="ollama/llama3"`. So, I'm wondering if there is a Local way to use my LLM model. (I have to connect the local API port, like using  `client = InferenceClient("my-llm-host")`)

**Comment by unclecode** [comment]
I see, then the local client does it support OpenAI api interface?

**Comment by Chi-chicken** [comment]
@unclecode, I afraid that the local client doesn't support OpenAI api interface. Because I'm using the Intranet.

**Comment by unclecode** [comment]
> @unclecode, I afraid that the local client doesn't support OpenAI api interface. Because I'm using the Intranet.

Then can you show me a sample of how u call this interface? Then I may be able to suggest something

**Comment by dcolley** [comment]
I solved this by selecting provider from `openai/*` adding the `base_url` param
```py
result = crawler.run(
        url=url,
        extraction_strategy=LLMExtractionStrategy(
            provider="openai/llama2",
            api_token="lm-studio",
            base_url="http://10.10.10.55:1234/v1",
            instruction="Extract only content related to PLM"
        ),
       bypass_cache=True,
)
```
