### ISSUE TITLE
CosineStrategy not exist in chunking_strtegy.py

### ISSUE THREAD

**Issue by USTAADCOM** [unclecode/crawl4ai#56]
ImportError: cannot import name 'CosineStrategy' from 'crawl4ai.chunking_strategy' (/home/aamir/Web Crawling with Vision Models/crawl4ai/crawl4ai/chunking_strategy.py)

**Comment by unclecode** [comment]
@USTAADCOM can you provide more details about your code? It seems like a weird error. Share some context so I can assist better. Also, if you want to use CosineStrategy, make sure to install the library this way:

```
pip install "crawl4ai[torch] @ git+https://github.com/unclecode/crawl4ai.git"
```

Check [https://crawl4ai.com/mkdocs/installation/](https://crawl4ai.com/mkdocs/installation/)
