### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by xixiskynet** [unclecode/crawl4ai#6]
No matching distribution found for onnxruntime

**Comment by unclecode** [comment]
I assume you are running it one a M1 silicon chip. Correct em if I am wrong. In that case try `conda install onnxruntime -c conda-forge` and if not then try to use this  https://github.com/cansik/onnxruntime-silicon

**Comment by OSH212** [comment]
same error, and i'm running the code on a mac/intel. Getting rid of the version specification in requirements.txt fixed all these errors for me (error was first caused by  onnxruntime, then html2text and torch).

**Comment by unclecode** [comment]
I see, interesting, thx for sharing the solution, already updated requirements.txt.
