### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by aravindkarnam** [unclecode/crawl4ai#62]
## Issue description
With the latest release in google-chrome-stable(version 127.0.6533.72), when we run the crawler it's throwing the following error `OSError: [Errno 8] Exec format error: '/root/.wdm/drivers/chromedriver/linux64/127.0.6533.72/chromedriver-linux64/THIRD_PARTY_NOTICES.chromedriver'`. You'll get this error only if you rebuild your docker image to install latest chrome.

## Suggestion
Looks like its due to `webdriver_manager` confusing a new file called `THIRD_PARTY_NOTICES.chromedriver` file in the latest release for actual driver. `webdriver_manager` fixed this in latest version `4.0.2` as per this [issue](https://github.com/SergeyPirogov/webdriver_manager/issues/665). Crawl4ai is currently using `4.0.1`, if we can bump this up we can use chrome latest version without any hassle. I've already checked out this version of webdriver_manager with crawl4ai on a ubuntu ec2 instance and it works as expected.

## Workaround in the meantime
In the meantime for anyone who come across this issue, the following [patch](https://stackoverflow.com/a/78790315/4753653) actually works. You can install this patch between the pip install and uvicorn startup commands in the dockerfile and current version of crawl4ai will work - or you can also force install the latest version of webdriver_manager.
__
@unclecode please consider updating the dockerfile to remove the installation of chrome driver. Since you introduced `ChromeDriverManger` in V 0.2.71, this line has become redundant. It's also confusing, I was trying to fix the issue at first by updating the dockerfile, only to later realise crawl4ai is installing and running different chrome driver.

**Comment by unclecode** [comment]
@aravindkarnam That's very true, I removed it already and will release soon in the version 0.2.76

**Comment by Emekaborisama** [comment]
i am having this same issue

**Comment by shamikct** [comment]
@unclecode Thanks for fixing it. Will the requirements be updates to install `webdriver_manager==4.0.2` in v0.2.76 ?
when will v0.2.76 be released?

**Comment by shamikct** [comment]
> i am having this same issue

Follow what @aravindkarnam has suggested and it should solve it.

**Comment by nicosalto** [comment]
I am having this issue too, but not in docker, when i install the default install on ubuntu. 
what is the process to fix this issue ?
you mentioned to update webdriver_manager to v4.0.2, but when i update this package i only get v4.0.1 ...

**Comment by shamikct** [comment]
4.0.2 is available https://pypi.org/project/webdriver-manager/

**Comment by shamikct** [comment]
Delete the ~/.wdm directory, if it exists.

*Thanks and Regards*
*Shamik*

*Book a quick meeting <https://calendar.app.google/ouhB3XrYiXSXmRwg6>*

*CODE AND THEORY*

Ad Age Business Transformation Agency of the Year

Shamik Biswas
Lead Engineer - Machine Learning

India
No 2, Prestige Emerald
State Bank of India road, Lavelle Road
Bangalore - 560 001

O: +91 80 41106986
www.codeandtheory.com
LinkedIn <https://www.linkedin.com/company/code-and-theory> | X
<https://x.com/codeandtheory> | Instagram
<https://www.instagram.com/codeandtheory>

**Comment by unclecode** [comment]
@shamikct @nicosalto @Emekaborisama @aravindkarnam  Tomorrow, I will release the new versions, tested on all three platforms, and a Docker image will be available on Docker Hub. Additionally, there's no longer a need for webdriver_manager, simplifying the process.
