### ISSUE TITLE
Fix `Exec format error: THIRD_PARTY_NOTICES.chromedrive`  by updating webdriver-manager to 4.0.2 

### ISSUE THREAD

**Issue by dylansheffer** [unclecode/crawl4ai#67]
Hello! I love the project and I am currently building out an application that uses it. However, there was a [bug in webdriver-manager](https://github.com/SergeyPirogov/webdriver_manager/issues/670) where the third party notices file was accidentally marked as the executable. [This bug has been fixed in 4.0.2](https://github.com/SergeyPirogov/webdriver_manager/releases/tag/v4.0.2) which fixes the issue. I have also forked crawl4ai and tested that updating the dependency fixes the issue for this project.

I'm happy to open a PR from my fork if you'd like.

Thanks again for the hard work!

**Comment by unclecode** [comment]
This issue has been resolved in v0.2.77 and later, so I will close it. Please let me know if you encounter any difficulties.
