### ISSUE TITLE
Question about extract link 

### ISSUE THREAD

**Issue by xwt1** [unclecode/crawl4ai#69]
Hello! Firstly, thank you for the excellent work! I have a question about extracting specific links using the strategy described at [crawl4ai LLM Extraction Example](https://crawl4ai.com/mkdocs/examples/llm_extraction/). I want to use this strategy to extract the specific links I'm interested in. I understand that I can use result.links as described in the [crawl4ai Crawl Result Class](https://crawl4ai.com/mkdocs/full_details/crawl_result_class/) to filter and extract the desired content. 
However, I am interested in knowing if it's possible to use LLMExtractionStrategy to extract the specific links I want. I managed to extract links, but I only obtained the link text, not with URLs. It seems that the URLs are not being delivered to the language model. Is there a way to achieve this by passing the URLs to the language model?

**Comment by unclecode** [comment]
@xwt1 Very interesting case, let me try today, I have an idea already

**Comment by unclecode** [comment]
Ok, the thing is, the LLM extraction strategy uses the extracted markdown, which doesn't include those links, so it doesn't apply them. However, you can use the LLM extraction separately from the crawler and fit it with whatever you want, like all the links. That's what I've done in this example. Take a look at it.

```
url = r"https://www.nbcnews.com/business"
result = crawler.run( url, word_count_threshold=0, bypass_cache=True, bypass_headless = False)

class PotentialLinks(BaseModel):
    link: str = Field(..., description="Potential link found in the content.")
    reason: str = Field(..., description="Reason for the link to be considered as potential link.")
    
llm_extraction_strategy = LLMExtractionStrategy(
        provider= "openai/gpt-4o-mini", api_token = os.getenv('OPENAI_API_KEY'), 
        # provider= "groq/llama3-70b-8192", api_token = os.getenv('OPENAI_API_KEY'), 
        schema=PotentialLinks.model_json_schema(),
        extraction_type="schema",
        instruction="""For a list of all given external links, try to extract all potential links from the content. A potential link refers to an authentic source. Your response should be in JSON format with the following structure: { "link": "https://www.example.com", "reason": "This link is a potential link because it is mentioned in the content." }"""
    )

internal = '\n'.join([a['href'] for a in result.links['internal']])
external = '\n'.join([a['href'] for a in result.links['external']])

potential_links = llm_extraction_strategy.run(url, [external])
```
