### ISSUE TITLE
Is Numpy requirement for Default Installation/Basic functionality ?

### ISSUE THREAD

**Issue by aravindkarnam** [unclecode/crawl4ai#70]
Is Numpy requirement for Default Installation/Basic functionality? If so we have to add it as such. Currently if you install crawl4ai into blank python environment without any packages pre-installed (unlike google colab), creating web crawler is failing because numpy is not installed. It works after you manually install numpy, but pip doesn't seem to automatically grasp numpy as requirement when you install crawl4ai default.

**Comment by unclecode** [comment]
@aravindkarnam I actually added to default requirements, there is a need for it, I push it soon, thx for reminding me.
