### ISSUE TITLE
Is there any way to get the page links?

### ISSUE THREAD

**Issue by rubenssoto** [unclecode/crawl4ai#72]
Hello,

I'm trying to get the link of every article from this blog: https://airbyte.com/blog-categories/engineering
is there any way to do that?

Thank you.

**Comment by unclecode** [comment]
@rubenssoto Sorry for the late response. You can simply call the `crawler.run()` and in response you have all the internal and external links.

```python
from crawl4ai.web_crawler import WebCrawler
crawler = WebCrawler()
crawler.warmup()
url = r"https://airbyte.com/blog-categories/engineering"
# If you want a fresh crawl every time set bypass_cache to True
result = crawler.run(url, word_count_threshold=0, bypass_cache=True, bypass_headless = False)
print(result.links['internal'])
```

**Comment by rubenssoto** [comment]
@unclecode thank you so much, it worked perfectly!!
