### ISSUE TITLE
How to show the browser for crawl? 

### ISSUE THREAD

**Issue by takan1** [unclecode/crawl4ai#79]
How to show the browser for crawl? It seems like the default is headless as I don't see a browser pops . The visible browser is helpful for js code building.

**Comment by aravindkarnam** [comment]
@takan1 You can use a browser extension like [tampermonkey](https://www.tampermonkey.net/) for js code building. Once you see that your js code is working as expected, then you can copy paste your JS code into your python script as shown [here.](https://crawl4ai.com/mkdocs/examples/js_execution_css_filtering/).  If you still think browser is needed to be displayed, could you please further explain the use case you are trying to code in JS?

**Comment by unclecode** [comment]
@takan1 The `crawler.run()` has this parameter `bypass_headless` and if you set it to `True` you can have the browser too.

```
result = crawler.run( url, bypass_cache=True, bypass_headless = False)
```
