### ISSUE TITLE
Is it possible to extract with LLMExtractionStrategy from markdown or cleaned_html (Not from html)? 

### ISSUE THREAD

**Issue by takan1** [unclecode/crawl4ai#82]
Is it possible to extract with LLMExtractionStrategy from markdown or cleaned_html (Not from html)?

**Comment by unclecode** [comment]
@takan1 Right now you can use it in this way:

```
result = crawler.run( r"https://www.nbcnews.com/business", word_count_threshold=0)
from crawl4ai.extraction_strategy import LLMExtractionStrategy
llm_extraction_strategy = LLMExtractionStrategy(
        provider= "openai/gpt-4o-mini", api_token = os.getenv('OPENAI_API_KEY'),
        instruction="""Extract headers fromt his markdown content"""
)
extraction_result = llm_extraction_strategy.run("", [result.markdown])
print(extraction_result)
```

However it seems to me a good option to add to the library.

**Comment by y0hnn** [comment]
It would be very useful to also have `cleaned_html` in the input_format. For example if we are scraping a big html and we would like to use less tokens for LLM by striping out useless tags.
