### ISSUE TITLE
Crawl4 AI是否支持自定义LLM

### ISSUE THREAD

**Issue by Hesongwork** [unclecode/crawl4ai#87]
Crawl4 AI是否支持自定义LLM

**Comment by navin-hariharan** [comment]
@Hesongwork Yes it does! What would you like to use?

**Comment by unclecode** [comment]
@Hesongwork Crawl4AI supports Ollama, so you can use any LLM that Ollama supports. For the actual crawling, we don’t rely on LLMs, which is key to making it fast. LLMs come into play when you need to extract semantically structured output. In the new version, you can even create specific JSON schemas using CSS selectors to extract patterns (like from e-commerce sites) super quickly, reducing the need for LLMs and keeping things efficient. But of course, we still support LLM extraction if needed, and you can use any LLM you like!
