### ISSUE TITLE
Restrict Certain HTML Tags (e.g., li, span) in Web Crawling

### ISSUE THREAD

**Issue by roshan-sinha-dev** [unclecode/crawl4ai#91]
While using crawl4ai for web scraping, we have encountered the need to restrict specific HTML tags such as <li> and <span> during the crawling process. These tags often introduce noise or unnecessary elements that do not contribute valuable data for certain scraping tasks, especially when extracting content-rich elements like paragraphs or headers.

**Comment by unclecode** [comment]
@roshan-sinha-dev Hi sorry for my delay,  you can achieve this using the css_selector. For example if you want to ignore `nav` and its children you can pass `*:not(nav):not(nav *)`, look at the following code:

```python

# List of tags to exclude from crawling
excluded_tags = [
    "nav",    
    "aside", 
    "footer", 
    "header",
    "form",   
    "noscript", 
    "iframe", 
    "script", 
    "style",  
    "link",   
    "input",  
    "button" 
]

# Function to convert the list of excluded tags to a CSS selector
def generate_css_selector(tags):
    # Join each tag with :not() and chain them
    return '*{}'.format(''.join(f':not({tag})' for tag in tags))

# Generate the CSS selector
css_selector = generate_css_selector(excluded_tags)

result = crawler.run(
    url="https://www.nbcnews.com/business",
    word_count_threshold=0,
    bypass_cache=True,
    css_selector=css_selector
)

print(len(result.markdown))
```

This code targets around 1600 html tags while without this, will be 1800+.

**Comment by roshan-sinha-dev** [comment]
Thank you @unclecode But it sometimes seems to be not working I tried for a few tags like "a" or "li" but it is still crawling those tags those tags

**Comment by unclecode** [comment]
I see @roshan-sinha-dev can you send me your code script with the website you're trying to crawl, I can test for you and see what is wrong.

**Comment by roshan-sinha-dev** [comment]
from crawl4ai import WebCrawler
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Create an instance of WebCrawler
crawler = WebCrawler()

# Warm up the crawler (load necessary models)
crawler.warmup()

excluded_tags = [
    "li",
    "span",
    "a",
    "ul"
]


def generate_css_selector(tags):
    # Join each tag with :not() and chain them
    return '*{}'.format(''.join(f':not({tag})' for tag in tags))

css_selector = generate_css_selector(excluded_tags)

print(css_selector)

# Run the crawler on a URL
result = crawler.run(url="https://iimamritsar.ac.in/p/director", css_selector=css_selector)


print(result.markdown)

**Comment by unclecode** [comment]
@roshan-sinha-dev You are right, try this approach plz:

```python
def after_get_url(driver):
        print("[HOOK] after_get_url")
        driver.execute_script("""document.querySelectorAll('li, ul, span, a').forEach(el => el.remove());""")
        return driver

crawler_strategy = LocalSeleniumCrawlerStrategy(verbose=True)
crawler_strategy.set_hook('after_get_url', after_get_url)
new_crawler = WebCrawler(verbose=True, crawler_strategy=crawler_strategy)
new_crawler.warmup()    
result = new_crawler.run(url="https://iimamritsar.ac.in/p/director", bypass_cache=True)
```

I tested, the final markdown doesn't have any of those tags.

**Comment by roshan-sinha-dev** [comment]
Thank you @unclecode  it is working now!!!!

**Comment by unclecode** [comment]
@roshan-sinha-dev in new release, we will add an extra parameter `excluded_tags` and handle this internally.
