### ISSUE TITLE
fix github description scrapper -> scraper

### ISSUE THREAD

**Issue by dyigitpolat** [unclecode/crawl4ai#92]
the same error is also seen in some HTML pages in the source.

**Comment by unclecode** [comment]
@dyigitpolat Thx we fixed it already.

**Comment by dyigitpolat** [comment]
Maybe it takes some time for GitHub to update... 
<img width="867" alt="image" src="https://github.com/user-attachments/assets/476f828a-120f-4c80-b7b9-c39c21bb6fb1">
<img width="286" alt="image" src="https://github.com/user-attachments/assets/c76b0502-b9be-4f05-a152-0578e30eea67">
