### ISSUE TITLE
js load more not working

### ISSUE THREAD

**Issue by anyangml** [unclecode/crawl4ai#94]
First of all, thank you for developing this tool.

trying to scrap the following page 

```

from crawl4ai.web_crawler import WebCrawler
crawler = WebCrawler()
crawler.warmup()

js_code = """
const loadMoreButton = document.querySelector('.Tbl__btn');
loadMoreButton.click();
"""


start = time.time()
url = r"https://icodrops.com/category/active-ico/"
result = crawler.run( url, word_count_threshold=5, bypass_cache=True, css_selector = "p.Cll-Project__name", js=js_code)
end = time.time()
print(result.markdown)

```
for some reason, it seems the js execution is not working.

**Comment by jonymusky** [comment]
I encountered the same issue as fixed in [this PR](https://github.com/unclecode/crawl4ai/pull/95). Hopefully, this can be merged soon so other engineers can benefit from having JS execution working as well.

**Comment by anyangml** [comment]
> I encountered the same issue as fixed in [this PR](https://github.com/unclecode/crawl4ai/pull/95). Hopefully, this can be merged soon so other engineers can benefit from having JS execution working as well.

unfortunately, this does not work for me.

**Comment by jonymusky** [comment]
@anyangml The JS was executed, but the page was taking longer to load the results (I confirmed this by using the screenshot feature).

I’ve updated the PR to include wait_for. With this addition, my PR and your code should work together smoothly.

```
import base64
from crawl4ai import WebCrawler
from crawl4ai.crawler_strategy import LocalSeleniumCrawlerStrategy
from selenium.webdriver.common.by import By
js_code = """document.querySelector('.Tbl__btn').click();"""
def wait_for_150_rows(driver):
    elements = driver.find_elements(By.CSS_SELECTOR, '.Tbl-Row')
    return len(elements) >= 150

crawler_strategy = LocalSeleniumCrawlerStrategy(js_code=js_code)
crawler = WebCrawler(crawler_strategy=crawler_strategy)
crawler.warmup()

result = crawler.run(
    url="https://icodrops.com/category/active-ico/",
    bypass_cache=True,
    screenshot=True,
    wait_for=wait_for_150_rows
)
        
print(result.markdown)
```

**Comment by unclecode** [comment]
_@jonymusky Really appreciate your help and PR! This week, we’ll be releasing the new version, which will be 100% async and use Playwright. There’s a similar concept to what you proposed here, to let users define criteria for async JS tasks. I’ve merged your PR into our staging branch for the sync version, and I’ll also add you to our contributors. Many thanks again!
