### ISSUE TITLE
How to scroll down in webpages using WebCrawler

### ISSUE THREAD

**Issue by JaviMota** [unclecode/crawl4ai#97]
Hi

Im wondering how could I interact with a webpage that you need to scroll down to get all the fields in the html.
I have tried to write a javascript code following the example of the button you provide, but seems to not have any effect and not raising any error.
Do you have any example for that?

Thank you.

**Comment by unclecode** [comment]
@JaviMota Please refer to this issue https://github.com/unclecode/crawl4ai/issues/86

This is a duplicate issue so I close it, thx for using Crawl4ai.
